import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type LanguageCode = 'en' | 'hi' | 'te' | 'mr' | 'bn' | 'ta' | 'kn' | 'ml' | 'pa' | 'gu' | 'or' | 'as';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation & Global
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    back: 'Back',
    common: 'Common',
    loading: 'Loading...',
    error: 'Something went wrong',
    success: 'Success!',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    
    // Landing Page
    appName: 'My HealthBot',
    motto: 'Your 24/7 Caring Virtual Companion for a Healthier Life',
    landingTitle: 'Your Health, Our Priority',
    landingSubtitle: 'Connect with healthcare professionals, get instant medical advice, and maintain your wellness journey with our AI-powered health assistant.',
    getStarted: 'Get Started',
    
    // Login Page
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to continue your health journey',
    email: 'Email',
    password: 'Password',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    signIn: 'Sign In',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    forgotPassword: 'Forgot Password?',
    
    // Register Page
    registerTitle: 'Create Account',
    registerSubtitle: 'Join thousands of users on their health journey',
    fullName: 'Full Name',
    phone: 'Phone Number',
    confirmPassword: 'Confirm Password',
    namePlaceholder: 'Enter your full name',
    phonePlaceholder: 'Enter your phone number',
    confirmPasswordPlaceholder: 'Confirm your password',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    
    // Home Page
    welcome: 'Welcome',
    dashboardTitle: 'Health Dashboard',
    bookAppointment: 'Book Appointment',
    emergencySOS: 'Emergency SOS',
    healthCheckup: 'Health Checkup',
    dietSuggestions: 'Diet Suggestions',
    exercisePlans: 'Exercise Plans',
    mentalHealth: 'Mental Health Support',
    healthReports: 'Health Reports', 
    
    // Symptom Scanner
    symptomScanner: 'Symptom Scanner',
    scanSymptoms: 'Scan Symptoms',

    // Book Appointment Modal
    bookAppointmentTitle: 'Book Appointment',
    scheduleConsultation: 'Schedule your consultation',
    patientDetails: 'Patient Details',
    doctorSelection: 'Doctor Selection',
    appointmentDetails: 'Appointment Details',
    previousReports: 'Previous Reports',
    uploadReportFormats: 'Supported formats: PDF, JPG, PNG (Max 10MB)',
    uploadReportNote: 'Upload previous medical reports (Max 5 files)',
    uploadReportTitle: 'Upload New Report',
    selectDoctor: 'Select Doctor',
    chooseDoctor: 'Choose a doctor',
    uploadFile: 'Upload File',
    reportType: 'Report Type',
    reportDate: 'Report Date',
    selectReportType: 'Select report type',
    bloodTest: 'Blood Test',
    xray: 'X-Ray',
    mri: 'MRI',
    ctscan: 'CT Scan',
    ultrasound: 'Ultrasound',
    ecg: 'ECG',
    prescription: 'Prescription',
    other: 'Other',
    notes: 'Notes',
    notesPlaceholder: 'Add any additional notes...',
    yourReports: 'Your Reports',
    noReports: 'No reports uploaded yet',
    uploadFirstReport: 'Upload your first medical report above',
    download: 'Download',
    failedToFetchReports: 'Failed to load your reports. Please try again.',
    uploading: 'Uploading...',
    uploadReport: 'Upload Report',
    reportUploaded: 'Report uploaded successfully!',
    fileUploadFailed: 'Failed to upload report. Please try again.',
    
    // Emergency Modal
    emergencyS0STitle: 'Emergency SOS',
    immediateHelp: 'Get immediate help',
    quickEmergencyContacts: 'Quick Emergency Contacts',
    reportEmergency: 'Report Emergency',
    emergencyType: 'Emergency Type',
    selectEmergencyType: 'Select emergency type',
    medicalEmergency: 'Medical Emergency',
    accident: 'Accident',
    fire: 'Fire',
    crime: 'Crime/Violence',
    mentalHealthCrisis: 'Mental Health Crisis',
    currentLocation: 'Current Location',
    locationPlaceholder: 'Enter your current location',
    getDescription: 'Description',
    descriptionPlaceholder: 'Describe the emergency situation...',
    emergencyContactName: 'Emergency Contact Name',
    contactNamePlaceholder: 'Contact person name',
    emergencyContactPhone: 'Emergency Contact Phone',
    contactPhonePlaceholder: 'Contact phone number',
    submitEmergency: 'Submit Emergency',
    importantNotice: 'Important Notice',
    emergencyNoticeContent: 'For immediate life-threatening emergencies, call 911 directly. This form is for reporting and tracking purposes and may not provide immediate response.',
    getYourLocation: 'Get My Location',
    submitting: 'Submitting...',
    emergencySent: 'Emergency request submitted! Help is on the way.',
    emergencyFailed: 'Failed to submit emergency report. Please call 911 directly.',
    
    // Chatbot Modal
    chatAssistantTitle: 'HealthBot Assistant',
    chatAssistantSubtitle: 'Your AI-powered health companion',
    askHealthQuestion: 'Ask a health question...'
  },
  hi: {
    // Navigation & Global
    login: 'लॉग इन',
    register: 'पंजीकरण',
    logout: 'लॉग आउट',
    back: 'वापस',
    common: 'सामान्य',
    loading: 'लोड हो रहा है...',
    error: 'कुछ गलत हो गया',
    success: 'सफलता!',
    cancel: 'रद्द करें',
    save: 'सेव करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    
    // Landing Page
    appName: 'माय हेल्थबॉट',
    motto: 'स्वस्थ जीवन के लिए आपका 24/7 देखभाल करने वाला वर्चुअल साथी',
    landingTitle: 'आपका स्वास्थ्य, हमारी प्राथमिकता',
    landingSubtitle: 'स्वास्थ्य पेशेवरों से जुड़ें, तत्काल चिकित्सा सलाह प्राप्त करें, और हमारे AI-पावर्ड हेल्थ असिस्टेंट के साथ अपनी कल्याण यात्रा बनाए रखें।',
    getStarted: 'शुरू करें',
    
    // Login Page
    loginTitle: 'वापस स्वागत है',
    loginSubtitle: 'अपनी स्वास्थ्य यात्रा जारी रखने के लिए साइन इन करें',
    email: 'ईमेल',
    password: 'पासवर्ड',
    emailPlaceholder: 'अपना ईमेल दर्ज करें',
    passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    signIn: 'साइन इन',
    noAccount: 'कोई खाता नहीं है?',
    signUp: 'साइन अप',
    forgotPassword: 'पासवर्ड भूल गए?',
    
    // Register Page
    registerTitle: 'खाता बनाएं',
    registerSubtitle: 'अपनी स्वास्थ्य यात्रा पर हजारों उपयोगकर्ताओं से जुड़ें',
    fullName: 'पूरा नाम',
    phone: 'फोन नंबर',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    namePlaceholder: 'अपना पूरा नाम दर्ज करें',
    phonePlaceholder: 'अपना फोन नंबर दर्ज करें',
    confirmPasswordPlaceholder: 'अपने पासवर्ड की पुष्टि करें',
    createAccount: 'खाता बनाएं',
    alreadyHaveAccount: 'पहले से खाता है?',
    
    // Home Page
    welcome: 'स्वागत',
    dashboardTitle: 'स्वास्थ्य डैशबोर्ड',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
    emergencySOS: 'आपातकालीन SOS',
    healthCheckup: 'स्वास्थ्य जांच',
    dietSuggestions: 'आहार सुझाव',
    exercisePlans: 'व्यायाम योजनाएं',
    mentalHealth: 'मानसिक स्वास्थ्य सहायता',
    healthReports: 'स्वास्थ्य रिपोर्ट',
    
    // Symptom Scanner
    symptomScanner: 'लक्षण स्कैनर',
    scanSymptoms: 'लक्षण स्कैन करें',

    // Book Appointment Modal
    bookAppointmentTitle: 'अपॉइंटमेंट बुक करें',
    scheduleConsultation: 'अपनी परामर्श अनुसूची करें',
    patientDetails: 'रोगी विवरण',
    doctorSelection: 'डॉक्टर का चयन',
    appointmentDetails: 'अपॉइंटमेंट विवरण',
    previousReports: 'पिछली रिपोर्टें',
    uploadReportFormats: 'समर्थित प्रारूप: PDF, JPG, PNG (अधिकतम 10MB)',
    uploadReportNote: 'पिछली मेडिकल रिपोर्ट अपलोड करें (अधिकतम 5 फाइलें)',
    uploadReportTitle: 'नई रिपोर्ट अपलोड करें',
    selectDoctor: 'डॉक्टर चुनें',
    chooseDoctor: 'एक डॉक्टर चुनें',
    uploadFile: 'फाइल अपलोड करें',
    reportType: 'रिपोर्ट का प्रकार',
    reportDate: 'रिपोर्ट की तारीख',
    selectReportType: 'रिपोर्ट का प्रकार चुनें',
    bloodTest: 'रक्त परीक्षण',
    xray: 'एक्स-रे',
    mri: 'एमआरआई',
    ctscan: 'सीटी स्कैन',
    ultrasound: 'अल्ट्रासाउंड',
    ecg: 'ईसीजी',
    prescription: 'नुस्खा',
    other: 'अन्य',
    notes: 'नोट्स',
    notesPlaceholder: 'कोई अतिरिक्त नोट्स जोड़ें...',
    yourReports: 'आपकी रिपोर्टें',
    noReports: 'अभी तक कोई रिपोर्ट अपलोड नहीं की गई',
    uploadFirstReport: 'ऊपर अपनी पहली मेडिकल रिपोर्ट अपलोड करें',
    download: 'डाउनलोड करें',
    failedToFetchReports: 'आपकी रिपोर्ट लोड करने में विफल। कृपया फिर से कोशिश करें।',
    uploading: 'अपलोड हो रहा है...',
    uploadReport: 'रिपोर्ट अपलोड करें',
    reportUploaded: 'रिपोर्ट सफलतापूर्वक अपलोड हुई!',
    fileUploadFailed: 'रिपोर्ट अपलोड करने में विफल। कृपया फिर से कोशिश करें।',
    
    // Emergency Modal
    emergencyS0STitle: 'आपातकालीन SOS',
    immediateHelp: 'तत्काल सहायता प्राप्त करें',
    quickEmergencyContacts: 'त्वरित आपातकालीन संपर्क',
    reportEmergency: 'आपातकाल की रिपोर्ट करें',
    emergencyType: 'आपातकाल का प्रकार',
    selectEmergencyType: 'आपातकाल का प्रकार चुनें',
    medicalEmergency: 'चिकित्सा आपातकाल',
    accident: 'दुर्घटना',
    fire: 'आग',
    crime: 'अपराध/हिंसा',
    mentalHealthCrisis: 'मानसिक स्वास्थ्य संकट',
    currentLocation: 'वर्तमान स्थान',
    locationPlaceholder: 'अपना वर्तमान स्थान दर्ज करें',
    getDescription: 'विवरण',
    descriptionPlaceholder: 'आपातकालीन स्थिति का वर्णन करें...',
    emergencyContactName: 'आपातकालीन संपर्क का नाम',
    contactNamePlaceholder: 'संपर्क व्यक्ति का नाम',
    emergencyContactPhone: 'आपातकालीन संपर्क फोन',
    contactPhonePlaceholder: 'संपर्क फोन नंबर',
    submitEmergency: 'आपातकाल सबमिट करें',
    importantNotice: 'महत्वपूर्ण सूचना',
    emergencyNoticeContent: 'तत्काल जीवन-घातक आपात स्थितियों के लिए, सीधे 911 पर कॉल करें। यह फॉर्म रिपोर्टिंग और ट्रैकिंग उद्देश्यों के लिए है और तत्काल प्रतिक्रिया प्रदान नहीं कर सकता है।',
    getYourLocation: 'मेरा स्थान प्राप्त करें',
    submitting: 'सबमिट हो रहा है...',
    emergencySent: 'आपातकालीन अनुरोध सबमिट हो गया! सहायता रास्ते में है।',
    emergencyFailed: 'आपातकालीन रिपोर्ट सबमिट करने में विफल। कृपया सीधे 911 पर कॉल करें।',

    // Chatbot Modal
    chatAssistantTitle: 'हेल्थबॉट सहायक',
    chatAssistantSubtitle: 'आपका AI-शक्ती का स्वास्थ्य साथी',
    askHealthQuestion: 'एक स्वास्थ्य प्रश्न पूछें...'
  },
  te: {
    // Navigation & Global
    login: 'లాగిన్ చేయండి',
    register: 'నమోదు చేయండి',
    logout: 'లాగౌట్',
    back: 'వెనుకకు',
    common: 'సాధారణ',
    loading: 'లోడ్ అవుతోంది...',
    error: 'ఏదో తప్పు జరిగింది',
    success: 'విజయం!',
    cancel: 'రద్దు చేయండి',
    save: 'సేవ్ చేయండి',
    edit: 'సవరించండి',
    delete: 'తొలగించండి',
    
    // Landing Page
    appName: 'మై హెల్త్‌బాట్',
    motto: 'ఆరోగ్యకరమైన జీవితం కోసం మీ 24/7 సంరక్షణ వర్చువల్ సహచరుడు',
    landingTitle: 'మీ ఆరోగ్యం, మా ప్రాధాన్యత',
    landingSubtitle: 'వైద్య నిపుణులతో కనెక్ట్ అవ్వండి, తక్షణ వైద్య సలహా పొందండి మరియు మా AI-ఆధారిత ఆరోగ్య సహాయకుడితో మీ ఆరోగ్య ప్రయాణాన్ని కొనసాగించండి.',
    getStarted: 'ప్రారంభించండి',
    
    // Login Page
    loginTitle: 'తిరిగి స్వాగతం',
    loginSubtitle: 'మీ ఆరోగ్య ప్రయాణాన్ని కొనసాగించడానికి సైన్ ఇన్ చేయండి',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    emailPlaceholder: 'మీ ఇమెయిల్ నమోదు చేయండి',
    passwordPlaceholder: 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    signIn: 'సైన్ ఇన్',
    noAccount: 'ఖాతా లేదా?',
    signUp: 'సైన్ అప్',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    
    // Register Page
    registerTitle: 'ఖాతాను సృష్టించండి',
    registerSubtitle: 'ఆరోగ్య ప్రయాణంలో వేలాది మంది వినియోగదారులతో చేరండి',
    fullName: 'పూర్తి పేరు',
    phone: 'ఫోన్ నంబర్',
    confirmPassword: 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
    namePlaceholder: 'మీ పూర్తి పేరును నమోదు చేయండి',
    phonePlaceholder: 'మీ ఫోన్ నంబర్‌ను నమోదు చేయండి',
    confirmPasswordPlaceholder: 'మీ పాస్‌వర్డ్‌ను నిర్ధారించండి',
    createAccount: 'ఖాతాను సృష్టించండి',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    
    // Home Page
    welcome: 'స్వాగతం',
    dashboardTitle: 'ఆరోగ్య డాష్‌బోర్డు',
    bookAppointment: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
    emergencySOS: 'అత్యవసర SOS',
    healthCheckup: 'ఆరోగ్య తనిఖీ',
    dietSuggestions: 'ఆహార సూచనలు',
    exercisePlans: 'వ్యాయామ ప్రణాళికలు',
    mentalHealth: 'మానసిక ఆరోగ్య మద్దతు',
    healthReports: 'ఆరోగ్య నివేదికలు',
    
    // Symptom Scanner
    symptomScanner: 'లక్షణ స్కానర్',
    scanSymptoms: 'లక్షణాలను స్కాన్ చేయండి',

    // Book Appointment Modal
    bookAppointmentTitle: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
    scheduleConsultation: 'మీ సంప్రదింపులను షెడ్యూల్ చేయండి',
    patientDetails: 'రోగి వివరాలు',
    doctorSelection: 'డాక్టర్ ఎంపిక',
    appointmentDetails: 'అపాయింట్‌మెంట్ వివరాలు',
    previousReports: 'మునుపటి నివేదికలు',
    uploadReportFormats: 'మద్దతు ఉన్న ఫార్మాట్‌లు: PDF, JPG, PNG (గరిష్టంగా 10MB)',
    uploadReportNote: 'మునుపటి వైద్య నివేదికలను అప్‌లోడ్ చేయండి (గరిష్టంగా 5 ఫైళ్లు)',
    uploadReportTitle: 'కొత్త నివేదికను అప్‌లోడ్ చేయండి',
    selectDoctor: 'డాక్టర్‌ని ఎంచుకోండి',
    chooseDoctor: 'ఒక డాక్టర్‌ని ఎంచుకోండి',
    uploadFile: 'ఫైల్‌ను అప్‌లోడ్ చేయండి',
    reportType: 'నివేదిక రకం',
    reportDate: 'నివేదిక తేదీ',
    selectReportType: 'నివేదిక రకాన్ని ఎంచుకోండి',
    bloodTest: 'రక్త పరీక్ష',
    xray: 'ఎక్స్-రే',
    mri: 'ఎమ్మెరై',
    ctscan: 'సీటీ స్కాన్',
    ultrasound: 'అల్ట్రాసౌండ్',
    ecg: 'ఈసిజి',
    prescription: 'ప్రిస్క్రిప్షన్',
    other: 'ఇతర',
    notes: 'గమనికలు',
    notesPlaceholder: 'ఏవైనా అదనపు గమనికలను జోడించండి...',
    yourReports: 'మీ నివేదికలు',
    noReports: 'ఇప్పటివరకు నివేదికలు అప్‌లోడ్ చేయబడలేదు',
    uploadFirstReport: 'పైన మీ మొదటి వైద్య నివేదికను అప్‌లోడ్ చేయండి',
    download: 'డౌన్‌లోడ్ చేయండి',
    failedToFetchReports: 'మీ నివేదికలను లోడ్ చేయడంలో విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    uploading: 'అప్‌లోడ్ అవుతోంది...',
    uploadReport: 'నివేదికను అప్‌లోడ్ చేయండి',
    reportUploaded: 'నివేదిక విజయవంతంగా అప్‌లోడ్ చేయబడింది!',
    fileUploadFailed: 'నివేదికను అప్‌లోడ్ చేయడంలో విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',

    // Emergency Modal
    emergencyS0STitle: 'అత్యవసర SOS',
    immediateHelp: 'తక్షణ సహాయం పొందండి',
    quickEmergencyContacts: 'త్వరిత అత్యవసర పరిచయాలు',
    reportEmergency: 'అత్యవసర పరిస్థితిని నివేదించండి',
    emergencyType: 'అత్యవసర రకం',
    selectEmergencyType: 'అత్యవసర రకాన్ని ఎంచుకోండి',
    medicalEmergency: 'వైద్య అత్యవసర పరిస్థితి',
    accident: 'ప్రమాదం',
    fire: 'అగ్ని',
    crime: 'నేరం/హింస',
    mentalHealthCrisis: 'మానసిక ఆరోగ్య సంక్షోభం',
    currentLocation: 'ప్రస్తుత స్థానం',
    locationPlaceholder: 'మీ ప్రస్తుత స్థానాన్ని నమోదు చేయండి',
    getDescription: 'వివరణ',
    descriptionPlaceholder: 'అత్యవసర పరిస్థితిని వివరించండి...',
    emergencyContactName: 'అత్యవసర సంపర్కం పేరు',
    contactNamePlaceholder: 'సంపర్కం వ్యక్తి పేరు',
    emergencyContactPhone: 'అత్యవసర సంపర్కం ఫోన్',
    contactPhonePlaceholder: 'సంపర్కం ఫోన్ నంబర్',
    submitEmergency: 'అత్యవసర పరిస్థితిని సమర్పించండి',
    importantNotice: 'ముఖ్యమైన నోటీసు',
    emergencyNoticeContent: 'తక్షణ ప్రాణాపాయ అత్యవసర పరిస్థితులకు, నేరుగా 911కు కాల్ చేయండి. ఈ ఫారమ్ రిపోర్టింగ్ మరియు ట్రాకింగ్ ప్రయోజనాల కోసం మాత్రమే మరియు తక్షణ ప్రతిస్పందనను అందించకపోవచ్చు.',
    getYourLocation: 'నా స్థానాన్ని పొందండి',
    submitting: 'సమర్పణ జరుగుతోంది...',
    emergencySent: 'అత్యవసర అభ్యర్థన సమర్పించబడింది! సహాయం మార్గంలో ఉంది.',
    emergencyFailed: 'అత్యవసర నివేదికను సమర్పించడంలో విఫలమైంది. దయచేసి నేరుగా 911కు కాల్ చేయండి.',

    // Chatbot Modal
    chatAssistantTitle: 'హెల్త్‌బాట్ సహాయకుడు',
    chatAssistantSubtitle: 'మీ AI-ఆధారిత ఆరోగ్య సహచరుడు',
    askHealthQuestion: 'ఆరోగ్యానికి సంబంధించిన ప్రశ్న అడగండి...'
  },
  mr: {
    // Navigation & Global
    login: 'लॉग इन',
    register: 'नोंदणी करा',
    logout: 'लॉग आउट',
    back: 'मागे',
    common: 'सामान्य',
    loading: 'लोड होत आहे...',
    error: 'काहीतरी चूक झाली',
    success: 'यशस्वी!',
    cancel: 'रद्द करा',
    save: 'सेव्ह करा',
    edit: 'संपादित करा',
    delete: 'हटवा',
    
    // Landing Page
    appName: 'माय हेल्थबॉट',
    motto: 'निरोगी जीवनासाठी तुमचा २४/७ काळजी घेणारा व्हर्च्युअल साथीदार',
    landingTitle: 'तुमचं आरोग्य, आमची प्राथमिकता',
    landingSubtitle: 'आरोग्यसेवा व्यावसायिकांशी संपर्क साधा, त्वरित वैद्यकीय सल्ला मिळवा, आणि आमच्या AI-शक्तीच्या आरोग्य सहाय्यकासह तुमच्या आरोग्याचा प्रवास सुरू ठेवा.',
    getStarted: 'सुरुवात करा',
    
    // Login Page
    loginTitle: 'पुन्हा स्वागत आहे',
    loginSubtitle: 'तुमचा आरोग्य प्रवास सुरू ठेवण्यासाठी साइन इन करा',
    email: 'ईमेल',
    password: 'पासवर्ड',
    emailPlaceholder: 'तुमचा ईमेल प्रविष्ट करा',
    passwordPlaceholder: 'तुमचा पासवर्ड प्रविष्ट करा',
    signIn: 'साइन इन करा',
    noAccount: 'खाते नाही?',
    signUp: 'साइन अप करा',
    forgotPassword: 'पासवर्ड विसरलात?',
    
    // Register Page
    registerTitle: 'खाते तयार करा',
    registerSubtitle: 'तुमच्या आरोग्य प्रवासात हजारो वापरकर्त्यांसोबत सामील व्हा',
    fullName: 'पूर्ण नाव',
    phone: 'फोन नंबर',
    confirmPassword: 'पासवर्डची पुष्टी करा',
    namePlaceholder: 'तुमचं पूर्ण नाव प्रविष्ट करा',
    phonePlaceholder: 'तुमचा फोन नंबर प्रविष्ट करा',
    confirmPasswordPlaceholder: 'तुमच्या पासवर्डची पुष्टी करा',
    createAccount: 'खाते तयार करा',
    alreadyHaveAccount: 'आधीच खाते आहे?',
    
    // Home Page
    welcome: 'स्वागत',
    dashboardTitle: 'आरोग्य डॅशबोर्ड',
    bookAppointment: 'अपॉइंटमेंट बुक करा',
    emergencySOS: 'आपत्कालीन SOS',
    healthCheckup: 'आरोग्य तपासणी',
    dietSuggestions: 'आहार सूचना',
    exercisePlans: 'व्यायाम योजना',
    mentalHealth: 'मानसिक आरोग्य मदत',
    healthReports: 'आरोग्य अहवाल',
    
    // Symptom Scanner
    symptomScanner: 'लक्षण स्कॅनर',
    scanSymptoms: 'लक्षणे स्कॅन करा',

    // Book Appointment Modal
    bookAppointmentTitle: 'अपॉइंटमेंट बुक करा',
    scheduleConsultation: 'तुमच्या डॉक्टरांच्या भेटीचे वेळापत्रक तयार करा',
    patientDetails: 'रुग्ण तपशील',
    doctorSelection: 'डॉक्टर निवड',
    appointmentDetails: 'अपॉइंटमेंट तपशील',
    previousReports: 'मागील अहवाल',
    uploadReportFormats: 'समर्थित स्वरूप: PDF, JPG, PNG (जास्तीत जास्त 10MB)',
    uploadReportNote: 'मागील वैद्यकीय अहवाल अपलोड करा (जास्तीत जास्त 5 फाइल्स)',
    uploadReportTitle: 'नवीन अहवाल अपलोड करा',
    selectDoctor: 'डॉक्टर निवडा',
    chooseDoctor: 'एक डॉक्टर निवडा',
    uploadFile: 'फाइल अपलोड करा',
    reportType: 'अहवालाचा प्रकार',
    reportDate: 'अहवालाची तारीख',
    selectReportType: 'अहवालाचा प्रकार निवडा',
    bloodTest: 'रक्त तपासणी',
    xray: 'एक्स-रे',
    mri: 'एमआरआय',
    ctscan: 'सीटी स्कॅन',
    ultrasound: 'अल्ट्रासाउंड',
    ecg: 'ईसीजी',
    prescription: 'प्रिस्क्रिप्शन',
    other: 'इतर',
    notes: 'नोट्स',
    notesPlaceholder: 'कोणतेही अतिरिक्त नोट्स जोडा...',
    yourReports: 'तुमचे अहवाल',
    noReports: 'अद्याप कोणतेही अहवाल अपलोड केलेले नाहीत',
    uploadFirstReport: 'वर तुमची पहिली वैद्यकीय अहवाल अपलोड करा',
    download: 'डाउनलोड करा',
    failedToFetchReports: 'तुमचे अहवाल लोड करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    uploading: 'अपलोड होत आहे...',
    uploadReport: 'अहवाल अपलोड करा',
    reportUploaded: 'अहवाल यशस्वीरित्या अपलोड झाला!',
    fileUploadFailed: 'अहवाल अपलोड करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.',

    // Emergency Modal
    emergencyS0STitle: 'आपत्कालीन SOS',
    immediateHelp: 'त्वरित मदत मिळवा',
    quickEmergencyContacts: 'त्वरित आपत्कालीन संपर्क',
    reportEmergency: 'आपत्कालीन परिस्थितीची नोंद करा',
    emergencyType: 'आपत्कालीन प्रकार',
    selectEmergencyType: 'आपत्कालीन प्रकार निवडा',
    medicalEmergency: 'वैद्यकीय आपत्कालीन',
    accident: 'अपघात',
    fire: 'आग',
    crime: 'गुन्हा/हिंसा',
    mentalHealthCrisis: 'मानसिक आरोग्य संकट',
    currentLocation: 'सध्याचे स्थान',
    locationPlaceholder: 'तुमचं सध्याचे स्थान प्रविष्ट करा',
    getDescription: 'वर्णन',
    descriptionPlaceholder: 'आपत्कालीन परिस्थितीचे वर्णन करा...',
    emergencyContactName: 'आपत्कालीन संपर्काचे नाव',
    contactNamePlaceholder: 'संपर्क व्यक्तीचे नाव',
    emergencyContactPhone: 'आपत्कालीन संपर्क फोन',
    contactPhonePlaceholder: 'संपर्क फोन नंबर',
    submitEmergency: 'आपत्कालीन नोंदणी करा',
    importantNotice: 'महत्त्वाची सूचना',
    emergencyNoticeContent: 'जीवन-घातक आपत्कालीन परिस्थितीसाठी, थेट ९११ वर कॉल करा. हा फॉर्म केवळ नोंदणी आणि ट्रॅकिंगसाठी आहे आणि त्वरित प्रतिसाद देऊ शकत नाही.',
    getYourLocation: 'माझे स्थान मिळवा',
    submitting: 'नोंदणी होत आहे...',
    emergencySent: 'आपत्कालीन विनंती सबमिट झाली! मदत मार्गावर आहे.',
    emergencyFailed: 'आपत्कालीन अहवाल सबमिट करण्यात अयशस्वी. कृपया थेट ९११ वर कॉल करा.',

    // Chatbot Modal
    chatAssistantTitle: 'हेल्थबॉट सहाय्यक',
    chatAssistantSubtitle: 'तुमचा AI-शक्तीचा आरोग्य साथीदार',
    askHealthQuestion: 'एक आरोग्य प्रश्न विचारा...'
  },
  bn: {
    // Navigation & Global
    login: 'লগইন',
    register: 'রেজিস্টার',
    logout: 'লগআউট',
    back: 'ফিরে যান',
    common: 'সাধারণ',
    loading: 'লোড হচ্ছে...',
    error: 'কিছু একটা ভুল হয়েছে',
    success: 'সফল!',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    edit: 'সম্পাদনা',
    delete: 'মুছে ফেলুন',
    
    // Landing Page
    appName: 'আমার হেলথবট',
    motto: 'একটি স্বাস্থ্যকর জীবনের জন্য আপনার ২৪/৭ যত্নশীল ভার্চুয়াল সঙ্গী',
    landingTitle: 'আপনার স্বাস্থ্য, আমাদের অগ্রাধিকার',
    landingSubtitle: 'স্বাস্থ্য পেশাদারদের সাথে সংযোগ করুন, তাৎক্ষণিক চিকিৎসা পরামর্শ পান এবং আমাদের এআই-চালিত স্বাস্থ্য সহকারীর সাথে আপনার সুস্থতার যাত্রা চালিয়ে যান।',
    getStarted: 'শুরু করুন',
    
    // Login Page
    loginTitle: 'ফিরে স্বাগতম',
    loginSubtitle: 'আপনার স্বাস্থ্য যাত্রা চালিয়ে যেতে সাইন ইন করুন',
    email: 'ইমেল',
    password: 'পাসওয়ার্ড',
    emailPlaceholder: 'আপনার ইমেল লিখুন',
    passwordPlaceholder: 'আপনার পাসওয়ার্ড লিখুন',
    signIn: 'সাইন ইন',
    noAccount: 'কোনো অ্যাকাউন্ট নেই?',
    signUp: 'সাইন আপ',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    
    // Register Page
    registerTitle: 'অ্যাকাউন্ট তৈরি করুন',
    registerSubtitle: 'আপনার স্বাস্থ্য যাত্রায় হাজার হাজার ব্যবহারকারীর সাথে যোগ দিন',
    fullName: 'পুরো নাম',
    phone: 'ফোন নম্বর',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    namePlaceholder: 'আপনার পুরো নাম লিখুন',
    phonePlaceholder: 'আপনার ফোন নম্বর লিখুন',
    confirmPasswordPlaceholder: 'আপনার পাসওয়ার্ড নিশ্চিত করুন',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    alreadyHaveAccount: 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
    
    // Home Page
    welcome: 'স্বাগতম',
    dashboardTitle: 'স্বাস্থ্য ড্যাশবোর্ড',
    bookAppointment: 'অ্যাপয়েন্টমেন্ট বুক করুন',
    emergencySOS: 'জরুরি এসওএস',
    healthCheckup: 'স্বাস্থ্য পরীক্ষা',
    dietSuggestions: 'খাদ্য পরামর্শ',
    exercisePlans: 'ব্যায়াম পরিকল্পনা',
    mentalHealth: 'মানসিক স্বাস্থ্য সহায়তা',
    healthReports: 'স্বাস্থ্য রিপোর্ট',
    
    // Symptom Scanner
    symptomScanner: 'লক্ষণ স্ক্যানার',
    scanSymptoms: 'লক্ষণ স্ক্যান করুন',

    // Book Appointment Modal
    bookAppointmentTitle: 'অ্যাপয়েন্টমেন্ট বুক করুন',
    scheduleConsultation: 'আপনার পরামর্শের সময়সূচী করুন',
    patientDetails: 'রোগীর বিবরণ',
    doctorSelection: 'ডাক্তার নির্বাচন',
    appointmentDetails: 'অ্যাপয়েন্টমেন্ট বিবরণ',
    previousReports: 'পূর্ববর্তী রিপোর্ট',
    uploadReportFormats: 'সমর্থিত ফরম্যাট: PDF, JPG, PNG (সর্বাধিক 10MB)',
    uploadReportNote: 'পূর্ববর্তী মেডিকেল রিপোর্ট আপলোড করুন (সর্বাধিক 5 ফাইল)',
    uploadReportTitle: 'নতুন রিপোর্ট আপলোড করুন',
    selectDoctor: 'ডাক্তার নির্বাচন করুন',
    chooseDoctor: 'একজন ডাক্তার বেছে নিন',
    uploadFile: 'ফাইল আপলোড করুন',
    reportType: 'রিপোর্টের ধরণ',
    reportDate: 'রিপোর্টের তারিখ',
    selectReportType: 'রিপোর্টের ধরণ নির্বাচন করুন',
    bloodTest: 'রক্ত পরীক্ষা',
    xray: 'এক্স-রে',
    mri: 'এমআরআই',
    ctscan: 'সিটি স্ক্যান',
    ultrasound: 'আল্ট্রাসাউন্ড',
    ecg: 'ইসিজি',
    prescription: 'প্রেসক্রিপশন',
    other: 'অন্যান্য',
    notes: 'নোটস',
    notesPlaceholder: 'যেকোনো অতিরিক্ত নোট যোগ করুন...',
    yourReports: 'আপনার রিপোর্ট',
    noReports: 'এখনও কোনো রিপোর্ট আপলোড করা হয়নি',
    uploadFirstReport: 'উপরে আপনার প্রথম মেডিকেল রিপোর্ট আপলোড করুন',
    download: 'ডাউনলোড করুন',
    failedToFetchReports: 'আপনার রিপোর্ট লোড করতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    uploading: 'আপলোড হচ্ছে...',
    uploadReport: 'রিপোর্ট আপলোড করুন',
    reportUploaded: 'রিপোর্ট সফলভাবে আপলোড হয়েছে!',
    fileUploadFailed: 'রিপোর্ট আপলোড করতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',

    // Emergency Modal
    emergencyS0STitle: 'জরুরি SOS',
    immediateHelp: 'তাৎক্ষণিক সাহায্য পান',
    quickEmergencyContacts: 'দ্রুত জরুরি যোগাযোগ',
    reportEmergency: 'জরুরি অবস্থা রিপোর্ট করুন',
    emergencyType: 'জরুরি অবস্থার ধরণ',
    selectEmergencyType: 'জরুরি অবস্থার ধরণ নির্বাচন করুন',
    medicalEmergency: 'চিকিৎসা জরুরি অবস্থা',
    accident: 'দুর্ঘটনা',
    fire: 'আগুন',
    crime: 'অপরাধ/হিংসা',
    mentalHealthCrisis: 'মানসিক স্বাস্থ্য সংকট',
    currentLocation: 'বর্তমান অবস্থান',
    locationPlaceholder: 'আপনার বর্তমান অবস্থান লিখুন',
    getDescription: 'বিবরণ',
    descriptionPlaceholder: 'জরুরি অবস্থার বিবরণ দিন...',
    emergencyContactName: 'জরুরি যোগাযোগের নাম',
    contactNamePlaceholder: 'যোগাযোগ ব্যক্তির নাম',
    emergencyContactPhone: 'জরুরি যোগাযোগের ফোন',
    contactPhonePlaceholder: 'যোগাযোগ ফোন নম্বর',
    submitEmergency: 'জরুরি অবস্থা জমা দিন',
    importantNotice: 'গুরুত্বপূর্ণ বিজ্ঞপ্তি',
    emergencyNoticeContent: 'তাৎক্ষণিক জীবন-হুমকিপূর্ণ জরুরি অবস্থার জন্য, সরাসরি 911 এ কল করুন। এই ফর্মটি শুধুমাত্র রিপোর্টিং এবং ট্র্যাকিংয়ের উদ্দেশ্যে এবং তাৎক্ষণিক প্রতিক্রিয়া নাও দিতে পারে।',
    getYourLocation: 'আমার অবস্থান পান',
    submitting: 'জমা দেওয়া হচ্ছে...',
    emergencySent: 'জরুরি অনুরোধ জমা দেওয়া হয়েছে! সাহায্য আসছে।',
    emergencyFailed: 'জরুরি রিপোর্ট জমা দিতে ব্যর্থ হয়েছে। সরাসরি 911 এ কল করুন।',

    // Chatbot Modal
    chatAssistantTitle: 'হেলথবট সহকারী',
    chatAssistantSubtitle: 'আপনার এআই-চালিত স্বাস্থ্য সঙ্গী',
    askHealthQuestion: 'একটি স্বাস্থ্য প্রশ্ন জিজ্ঞাসা করুন...'
  },
  ta: {
    // Navigation & Global
    login: 'உள்நுழை',
    register: 'பதிவுசெய்',
    logout: 'வெளியேறு',
    back: 'பின்செல்',
    common: 'பொதுவான',
    loading: 'ஏற்றுகிறது...',
    error: 'ஏதோ தவறு நடந்துவிட்டது',
    success: 'வெற்றிகரம்!',
    cancel: 'ரத்து செய்',
    save: 'சேமி',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    
    // Landing Page
    appName: 'மை ஹெல்த்பாட்',
    motto: 'ஆரோக்கியமான வாழ்க்கைக்கான உங்கள் 24/7 அக்கறையுள்ள மெய்நிகர் துணைவர்',
    landingTitle: 'உங்கள் ஆரோக்கியம், எங்கள் முன்னுரிமை',
    landingSubtitle: 'சுகாதார நிபுணர்களுடன் இணைந்திருங்கள், உடனடி மருத்துவ ஆலோசனை பெறுங்கள், மேலும் எங்கள் AI-இயங்கும் சுகாதார உதவியாளர் மூலம் உங்கள் ஆரோக்கிய பயணத்தைத் தொடருங்கள்.',
    getStarted: 'தொடங்கு',
    
    // Login Page
    loginTitle: 'மீண்டும் வருக',
    loginSubtitle: 'உங்கள் ஆரோக்கிய பயணத்தைத் தொடர உள்நுழையவும்',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    emailPlaceholder: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    passwordPlaceholder: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    signIn: 'உள்நுழைக',
    noAccount: 'கணக்கு இல்லையா?',
    signUp: 'பதிவு செய்க',
    forgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    
    // Register Page
    registerTitle: 'கணக்கை உருவாக்கு',
    registerSubtitle: 'உங்கள் ஆரோக்கிய பயணத்தில் ஆயிரக்கணக்கான பயனர்களுடன் இணையுங்கள்',
    fullName: 'முழு பெயர்',
    phone: 'தொலைபேசி எண்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    namePlaceholder: 'உங்கள் முழுப் பெயரை உள்ளிடவும்',
    phonePlaceholder: 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
    confirmPasswordPlaceholder: 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    createAccount: 'கணக்கை உருவாக்கு',
    alreadyHaveAccount: 'ஏற்கனவே ஒரு கணக்கு உள்ளதா?',
    
    // Home Page
    welcome: 'வரவேற்பு',
    dashboardTitle: 'ஆரோக்கிய டாஷ்போர்டு',
    bookAppointment: 'அப்பாயிண்ட்மென்ட் முன்பதிவு செய்',
    emergencySOS: 'அவசர SOS',
    healthCheckup: 'ஆரோக்கிய பரிசோதனை',
    dietSuggestions: 'உணவு பரிந்துரைகள்',
    exercisePlans: 'பயிற்சி திட்டங்கள்',
    mentalHealth: 'மனநல ஆதரவு',
    healthReports: 'சுகாதார அறிக்கைகள்',
    
    // Symptom Scanner
    symptomScanner: 'அறிகுறி ஸ்கேனர்',
    scanSymptoms: 'அறிகுறிகளை ஸ்கேன் செய்',

    // Book Appointment Modal
    bookAppointmentTitle: 'அப்பாயிண்ட்மென்ட் முன்பதிவு செய்',
    scheduleConsultation: 'உங்கள் ஆலோசனையை அட்டவணைப்படுத்தவும்',
    patientDetails: 'நோயாளி விவரங்கள்',
    doctorSelection: 'மருத்துவர் தேர்வு',
    appointmentDetails: 'அப்பாயிண்ட்மென்ட் விவரங்கள்',
    previousReports: 'முந்தைய அறிக்கைகள்',
    uploadReportFormats: 'ஆதரவு வடிவங்கள்: PDF, JPG, PNG (அதிகபட்சம் 10MB)',
    uploadReportNote: 'முந்தைய மருத்துவ அறிக்கைகளை பதிவேற்றவும் (அதிகபட்சம் 5 கோப்புகள்)',
    uploadReportTitle: 'புதிய அறிக்கையை பதிவேற்றவும்',
    selectDoctor: 'மருத்துவரைத் தேர்ந்தெடுக்கவும்',
    chooseDoctor: 'ஒரு மருத்துவரைத் தேர்ந்தெடுக்கவும்',
    uploadFile: 'கோப்பை பதிவேற்றவும்',
    reportType: 'அறிக்கை வகை',
    reportDate: 'அறிக்கை தேதி',
    selectReportType: 'அறிக்கை வகையைத் தேர்ந்தெடுக்கவும்',
    bloodTest: 'இரத்தப் பரிசோதனை',
    xray: 'எக்ஸ்-ரே',
    mri: 'எம்.ஆர்.ஐ',
    ctscan: 'சி.டி ஸ்கேன்',
    ultrasound: 'அல்ட்ராசவுண்ட்',
    ecg: 'ஈ.சி.ஜி',
    prescription: 'மருந்துச் சீட்டு',
    other: 'பிற',
    notes: 'குறிப்புகள்',
    notesPlaceholder: 'கூடுதல் குறிப்புகளைச் சேர்க்கவும்...',
    yourReports: 'உங்கள் அறிக்கைகள்',
    noReports: 'இதுவரை எந்த அறிக்கையும் பதிவேற்றப்படவில்லை',
    uploadFirstReport: 'மேலே உங்கள் முதல் மருத்துவ அறிக்கையை பதிவேற்றவும்',
    download: 'பதிவிறக்கு',
    failedToFetchReports: 'உங்கள் அறிக்கைகளை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    uploading: 'பதிவேற்றுகிறது...',
    uploadReport: 'அறிக்கையை பதிவேற்றவும்',
    reportUploaded: 'அறிக்கை வெற்றிகரமாக பதிவேற்றப்பட்டது!',
    fileUploadFailed: 'அறிக்கையை பதிவேற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    
    // Emergency Modal
    emergencyS0STitle: 'அவசர SOS',
    immediateHelp: 'உடனடி உதவி பெறு',
    quickEmergencyContacts: 'விரைவான அவசர தொடர்புகள்',
    reportEmergency: 'அவசரநிலையை அறிக்கை செய்',
    emergencyType: 'அவசரநிலை வகை',
    selectEmergencyType: 'அவசரநிலை வகையைத் தேர்ந்தெடுக்கவும்',
    medicalEmergency: 'மருத்துவ அவசரநிலை',
    accident: 'விபத்து',
    fire: 'தீ',
    crime: 'குற்றம்/வன்முறை',
    mentalHealthCrisis: 'மனநல நெருக்கடி',
    currentLocation: 'தற்போதைய இடம்',
    locationPlaceholder: 'உங்கள் தற்போதைய இடத்தை உள்ளிடவும்',
    getDescription: 'விளக்கம்',
    descriptionPlaceholder: 'அவசரநிலையின் சூழ்நிலையை விவரிக்கவும்...',
    emergencyContactName: 'அவசர தொடர்பு பெயர்',
    contactNamePlaceholder: 'தொடர்பு நபரின் பெயர்',
    emergencyContactPhone: 'அவசர தொடர்பு தொலைபேசி',
    contactPhonePlaceholder: 'தொடர்பு தொலைபேசி எண்',
    submitEmergency: 'அவசரநிலையை சமர்ப்பி',
    importantNotice: 'முக்கிய அறிவிப்பு',
    emergencyNoticeContent: 'உடனடி உயிருக்கு ஆபத்தான அவசரநிலைகளுக்கு, நேரடியாக 911-ஐ அழைக்கவும். இந்த படிவம் அறிக்கை மற்றும் கண்காணிப்பு நோக்கங்களுக்காக மட்டுமே. இது உடனடி பதிலைக் கொடுக்காது.',
    getYourLocation: 'எனது இருப்பிடத்தைப் பெறு',
    submitting: 'சமர்ப்பிக்கிறது...',
    emergencySent: 'அவசர கோரிக்கை சமர்ப்பிக்கப்பட்டது! உதவி வழியில் உள்ளது.',
    emergencyFailed: 'அவசர அறிக்கையை சமர்ப்பிக்க முடியவில்லை. நேரடியாக 911-ஐ அழைக்கவும்.',

    // Chatbot Modal
    chatAssistantTitle: 'ஹெல்த்பாட் உதவியாளர்',
    chatAssistantSubtitle: 'உங்கள் AI-இயங்கும் சுகாதார துணைவர்',
    askHealthQuestion: 'ஆரோக்கியம் தொடர்பான ஒரு கேள்வியை கேட்கவும்...'
  },
  kn: {
    // Navigation & Global
    login: 'ಲಾಗಿನ್',
    register: 'ನೋಂದಣಿ',
    logout: 'ಲಾಗ್ ಔಟ್',
    back: 'ಹಿಂದೆ',
    common: 'ಸಾಮಾನ್ಯ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    error: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
    success: 'ಯಶಸ್ಸು!',
    cancel: 'ರದ್ದುಮಾಡಿ',
    save: 'ಉಳಿಸು',
    edit: 'ಸಂಪಾದಿಸು',
    delete: 'ಅಳಿಸು',
    
    // Landing Page
    appName: 'ನನ್ನ ಹೆಲ್ತ್‌ಬಾಟ್',
    motto: 'ಆರೋಗ್ಯಕರ ಜೀವನಕ್ಕಾಗಿ ನಿಮ್ಮ 24/7 ಕಾಳಜಿಯುಳ್ಳ ವರ್ಚುವಲ್ ಸಂಗಾತಿ',
    landingTitle: 'ನಿಮ್ಮ ಆರೋಗ್ಯ, ನಮ್ಮ ಆದ್ಯತೆ',
    landingSubtitle: 'ಆರೋಗ್ಯ ವೃತ್ತಿಪರರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ, ತ್ವರಿತ ವೈದ್ಯಕೀಯ ಸಲಹೆ ಪಡೆಯಿರಿ ಮತ್ತು ನಮ್ಮ AI-ಚಾಲಿತ ಆರೋಗ್ಯ ಸಹಾಯಕದೊಂದಿಗೆ ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಯಾಣವನ್ನು ಮುಂದುವರಿಸಿ.',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    
    // Login Page
    loginTitle: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    loginSubtitle: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಯಾಣವನ್ನು ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್ವರ್ಡ್',
    emailPlaceholder: 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    passwordPlaceholder: 'ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
    signIn: 'ಸೈನ್ ಇನ್',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    signUp: 'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    forgotPassword: 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
    
    // Register Page
    registerTitle: 'ಖಾತೆ ರಚಿಸಿ',
    registerSubtitle: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಯಾಣದಲ್ಲಿ ಸಾವಿರಾರು ಬಳಕೆದಾರರೊಂದಿಗೆ ಸೇರಿಕೊಳ್ಳಿ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    confirmPassword: 'ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    namePlaceholder: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
    phonePlaceholder: 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    confirmPasswordPlaceholder: 'ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    
    // Home Page
    welcome: 'ಸ್ವಾಗತ',
    dashboardTitle: 'ಆರೋಗ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    bookAppointment: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',
    emergencySOS: 'ತುರ್ತು SOS',
    healthCheckup: 'ಆರೋಗ್ಯ ತಪಾಸಣೆ',
    dietSuggestions: 'ಆಹಾರ ಸಲಹೆಗಳು',
    exercisePlans: 'ವ್ಯಾಯಾಮ ಯೋಜನೆಗಳು',
    mentalHealth: 'ಮಾನಸಿಕ ಆರೋಗ್ಯ ಬೆಂಬಲ',
    healthReports: 'ಆರೋಗ್ಯ ವರದಿಗಳು',
    
    // Symptom Scanner
    symptomScanner: 'ಲಕ್ಷಣ ಸ್ಕ್ಯಾನರ್',
    scanSymptoms: 'ಲಕ್ಷಣಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',

    // Book Appointment Modal
    bookAppointmentTitle: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',
    scheduleConsultation: 'ನಿಮ್ಮ ಸಮಾಲೋಚನೆಯನ್ನು ನಿಗದಿಪಡಿಸಿ',
    patientDetails: 'ರೋಗಿಯ ವಿವರಗಳು',
    doctorSelection: 'ವೈದ್ಯರ ಆಯ್ಕೆ',
    appointmentDetails: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ವಿವರಗಳು',
    previousReports: 'ಹಿಂದಿನ ವರದಿಗಳು',
    uploadReportFormats: 'ಬೆಂಬಲಿತ ಸ್ವರೂಪಗಳು: PDF, JPG, PNG (ಗರಿಷ್ಠ 10MB)',
    uploadReportNote: 'ಹಿಂದಿನ ವೈದ್ಯಕೀಯ ವರದಿಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ (ಗರಿಷ್ಠ 5 ಫೈಲ್ಗಳು)',
    uploadReportTitle: 'ಹೊಸ ವರದಿಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    selectDoctor: 'ವೈದ್ಯರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    chooseDoctor: 'ವೈದ್ಯರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    uploadFile: 'ಫೈಲ್ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    reportType: 'ವರದಿ ಪ್ರಕಾರ',
    reportDate: 'ವರದಿ ದಿನಾಂಕ',
    selectReportType: 'ವರದಿಯ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    bloodTest: 'ರಕ್ತ ಪರೀಕ್ಷೆ',
    xray: 'ಎಕ್ಸ-ರೇ',
    mri: 'ಎಂಆರ್‌ಐ',
    ctscan: 'ಸಿಟಿ ಸ್ಕ್ಯಾನ್',
    ultrasound: 'ಅಲ್ಟ್ರಾಸೌಂಡ್',
    ecg: 'ಇಸಿಜಿ',
    prescription: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್',
    other: 'ಇತರ',
    notes: 'ಟಿಪ್ಪಣಿಗಳು',
    notesPlaceholder: 'ಯಾವುದೇ ಹೆಚ್ಚುವರಿ ಟಿಪ್ಪಣಿಗಳನ್ನು ಸೇರಿಸಿ...',
    yourReports: 'ನಿಮ್ಮ ವರದಿಗಳು',
    noReports: 'ಇನ್ನೂ ಯಾವುದೇ ವರದಿಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿಲ್ಲ',
    uploadFirstReport: 'ನಿಮ್ಮ ಮೊದಲ ವೈದ್ಯಕೀಯ ವರದಿಯನ್ನು ಮೇಲೆ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    download: 'ಡೌನ್‌ಲೋಡ್',
    failedToFetchReports: 'ನಿಮ್ಮ ವರದಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    uploading: 'ಅಪ್ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    uploadReport: 'ವರದಿ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    reportUploaded: 'ವರದಿ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್ಲೋಡ್ ಆಗಿದೆ!',
    fileUploadFailed: 'ವರದಿ ಅಪ್ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    
    // Emergency Modal
    emergencyS0STitle: 'ತುರ್ತು SOS',
    immediateHelp: 'ತಕ್ಷಣದ ಸಹಾಯ ಪಡೆಯಿರಿ',
    quickEmergencyContacts: 'ತ್ವರಿತ ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    reportEmergency: 'ತುರ್ತು ಪರಿಸ್ಥಿತಿ ವರದಿ ಮಾಡಿ',
    emergencyType: 'ತುರ್ತು ಪ್ರಕಾರ',
    selectEmergencyType: 'ತುರ್ತು ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    medicalEmergency: 'ವೈದ್ಯಕೀಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿ',
    accident: 'ಅಪಘಾತ',
    fire: 'ಬೆಂಕಿ',
    crime: 'ಅಪರಾಧ/ಹಿಂಸೆ',
    mentalHealthCrisis: 'ಮಾನಸಿಕ ಆರೋಗ್ಯ ಬಿಕ್ಕಟ್ಟು',
    currentLocation: 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
    locationPlaceholder: 'ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ನಮೂದಿಸಿ',
    getDescription: 'ವಿವರಣೆ',
    descriptionPlaceholder: 'ತುರ್ತು ಪರಿಸ್ಥಿತಿಯನ್ನು ವಿವರಿಸಿ...',
    emergencyContactName: 'ತುರ್ತು ಸಂಪರ್ಕ ಹೆಸರು',
    contactNamePlaceholder: 'ಸಂಪರ್ಕ ವ್ಯಕ್ತಿಯ ಹೆಸರು',
    emergencyContactPhone: 'ತುರ್ತು ಸಂಪರ್ಕ ಫೋನ್',
    contactPhonePlaceholder: 'ಸಂಪರ್ಕ ಫೋನ್ ಸಂಖ್ಯೆ',
    submitEmergency: 'ತುರ್ತು ಸಲ್ಲಿಸಿ',
    importantNotice: 'ಪ್ರಮುಖ ಸೂಚನೆ',
    emergencyNoticeContent: 'ತಕ್ಷಣದ ಜೀವಕ್ಕೆ ಅಪಾಯಕಾರಿ ತುರ್ತು ಪರಿಸ್ಥಿತಿಗಳಿಗಾಗಿ, ನೇರವಾಗಿ 911 ಗೆ ಕರೆ ಮಾಡಿ. ಈ ಫಾರ್ಮ್ ವರದಿ ಮಾಡುವ ಮತ್ತು ಟ್ರ್ಯಾಕಿಂಗ್ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ ಮತ್ತು ತಕ್ಷಣದ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ನೀಡದಿರಬಹುದು.',
    getYourLocation: 'ನನ್ನ ಸ್ಥಳ ಪಡೆಯಿರಿ',
    submitting: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    emergencySent: 'ತುರ್ತು ವಿನಂತಿ ಸಲ್ಲಿಸಲಾಗಿದೆ! ಸಹಾಯ ಬರುತ್ತಿದೆ.',
    emergencyFailed: 'ತುರ್ತು ವರದಿ ಸಲ್ಲಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ನೇರವಾಗಿ 911 ಗೆ ಕರೆ ಮಾಡಿ.',

    // Chatbot Modal
    chatAssistantTitle: 'ಹೆಲ್ತ್‌ಬಾಟ್ ಸಹಾಯಕ',
    chatAssistantSubtitle: 'ನಿಮ್ಮ AI-ಚಾಲಿತ ಆರೋಗ್ಯ ಸಂಗಾತಿ',
    askHealthQuestion: 'ಆರೋಗ್ಯ ಪ್ರಶ್ನೆ ಕೇಳಿ...'
  },
  ml: {
    // Navigation & Global
    login: 'ലോഗിൻ',
    register: 'രജിസ്റ്റർ',
    logout: 'ലോഗ് ഔട്ട്',
    back: 'പുറകിലേക്ക്',
    common: 'സാധാരണ',
    loading: 'ലോഡ് ചെയ്യുന്നു...',
    error: 'എന്തോ തകരാറ് സംഭവിച്ചു',
    success: 'വിജയം!',
    cancel: 'റദ്ദാക്കുക',
    save: 'സംരക്ഷിക്കുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    delete: 'ഡിലീറ്റ് ചെയ്യുക',
    
    // Landing Page
    appName: 'എന്റെ ഹെൽത്ത്ബോട്ട്',
    motto: 'ആരോഗ്യകരമായ ജീവിതത്തിനായി നിങ്ങളുടെ 24/7 കരുതലുള്ള വെർച്വൽ കൂട്ടാളി',
    landingTitle: 'നിങ്ങളുടെ ആരോഗ്യം, ഞങ്ങളുടെ മുൻഗണന',
    landingSubtitle: 'ആരോഗ്യ വിദഗ്ദ്ധരുമായി ബന്ധപ്പെടുക, തൽക്ഷണ വൈദ്യോപദേശം നേടുക, ഒപ്പം ഞങ്ങളുടെ AI-അധിഷ്ഠിത ആരോഗ്യ സഹായി ഉപയോഗിച്ച് നിങ്ങളുടെ ആരോഗ്യ യാത്ര തുടരുക.',
    getStarted: 'തുടങ്ങുക',
    
    // Login Page
    loginTitle: 'വീണ്ടും സ്വാഗതം',
    loginSubtitle: 'നിങ്ങളുടെ ആരോഗ്യ യാത്ര തുടരാൻ സൈൻ ഇൻ ചെയ്യുക',
    email: 'ഇമെയിൽ',
    password: 'പാസ്‌വേഡ്',
    emailPlaceholder: 'നിങ്ങളുടെ ഇമെയിൽ നൽകുക',
    passwordPlaceholder: 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക',
    signIn: 'സൈൻ ഇൻ',
    noAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    signUp: 'സൈൻ അപ്പ് ചെയ്യുക',
    forgotPassword: 'പാസ്‌വേഡ് മറന്നുപോയോ?',
    
    // Register Page
    registerTitle: 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    registerSubtitle: 'നിങ്ങളുടെ ആരോഗ്യ യാത്രയിൽ ആയിരക്കണക്കിന് ഉപയോക്താക്കളോടൊപ്പം ചേരുക',
    fullName: 'മുഴുവൻ പേര്',
    phone: 'ഫോൺ നമ്പർ',
    confirmPassword: 'പാസ്‌വേഡ് ഉറപ്പിക്കുക',
    namePlaceholder: 'നിങ്ങളുടെ മുഴുവൻ പേര് നൽകുക',
    phonePlaceholder: 'നിങ്ങളുടെ ഫോൺ നമ്പർ നൽകുക',
    confirmPasswordPlaceholder: 'നിങ്ങളുടെ പാസ്‌വേഡ് ഉറപ്പിക്കുക',
    createAccount: 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    alreadyHaveAccount: 'നിങ്ങൾക്ക് ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    
    // Home Page
    welcome: 'സ്വാഗതം',
    dashboardTitle: 'ആരോഗ്യ ഡാഷ്‌ബോർഡ്',
    bookAppointment: 'അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക',
    emergencySOS: 'അടിയന്തര SOS',
    healthCheckup: 'ആരോഗ്യ പരിശോധന',
    dietSuggestions: 'ഭക്ഷണ നിർദ്ദേശങ്ങൾ',
    exercisePlans: 'വ്യായാമ പദ്ധതികൾ',
    mentalHealth: 'മാനസിക ആരോഗ്യ പിന്തുണ',
    healthReports: 'ആരോഗ്യ റിപ്പോർട്ടുകൾ',
    
    // Symptom Scanner
    symptomScanner: 'ലക്ഷണ സ്കാനർ',
    scanSymptoms: 'ലക്ഷണങ്ങൾ സ്കാൻ ചെയ്യുക',

    // Book Appointment Modal
    bookAppointmentTitle: 'അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക',
    scheduleConsultation: 'നിങ്ങളുടെ കൺസൾട്ടേഷൻ ഷെഡ്യൂൾ ചെയ്യുക',
    patientDetails: 'രോഗിയുടെ വിവരങ്ങൾ',
    doctorSelection: 'ഡോക്ടറെ തിരഞ്ഞെടുക്കുക',
    appointmentDetails: 'അപ്പോയിന്റ്മെന്റ് വിവരങ്ങൾ',
    previousReports: 'മുമ്പത്തെ റിപ്പോർട്ടുകൾ',
    uploadReportFormats: 'പിന്തുണയ്ക്കുന്ന ഫോർമാറ്റുകൾ: PDF, JPG, PNG (പരമാവധി 10MB)',
    uploadReportNote: 'മുമ്പത്തെ മെഡിക്കൽ റിപ്പോർട്ടുകൾ അപ്‌ലോഡ് ചെയ്യുക (പരമാവധി 5 ഫയലുകൾ)',
    uploadReportTitle: 'പുതിയ റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക',
    selectDoctor: 'ഡോക്ടറെ തിരഞ്ഞെടുക്കുക',
    chooseDoctor: 'ഒരു ഡോക്ടറെ തിരഞ്ഞെടുക്കുക',
    uploadFile: 'ഫയൽ അപ്‌ലോഡ് ചെയ്യുക',
    reportType: 'റിപ്പോർട്ട് തരം',
    reportDate: 'റിപ്പോർട്ട് തീയതി',
    selectReportType: 'റിപ്പോർട്ട് തരം തിരഞ്ഞെടുക്കുക',
    bloodTest: 'രക്തപരിശോധന',
    xray: 'എക്സ്-റേ',
    mri: 'എംആർഐ',
    ctscan: 'സിടി സ്കാൻ',
    ultrasound: 'അൾട്രാസൗണ്ട്',
    ecg: 'ഇസിജി',
    prescription: 'കുറിപ്പടി',
    other: 'മറ്റുള്ളവ',
    notes: 'കുറിപ്പുകൾ',
    notesPlaceholder: 'ഏതെങ്കിലും അധിക കുറിപ്പുകൾ ചേർക്കുക...',
    yourReports: 'നിങ്ങളുടെ റിപ്പോർട്ടുകൾ',
    noReports: 'ഇതുവരെ റിപ്പോർട്ടുകളൊന്നും അപ്‌ലോഡ് ചെയ്തിട്ടില്ല',
    uploadFirstReport: 'നിങ്ങളുടെ ആദ്യ മെഡിക്കൽ റിപ്പോർട്ട് മുകളിൽ അപ്‌ലോഡ് ചെയ്യുക',
    download: 'ഡൗൺലോഡ് ചെയ്യുക',
    failedToFetchReports: 'നിങ്ങളുടെ റിപ്പോർട്ടുകൾ ലോഡ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    uploading: 'അപ്‌ലോഡ് ചെയ്യുന്നു...',
    uploadReport: 'റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക',
    reportUploaded: 'റിപ്പോർട്ട് വിജയകരമായി അപ്‌ലോഡ് ചെയ്തു!',
    fileUploadFailed: 'റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    
    // Emergency Modal
    emergencyS0STitle: 'അടിയന്തര SOS',
    immediateHelp: 'തൽക്ഷണ സഹായം നേടുക',
    quickEmergencyContacts: 'പെട്ടെന്നുള്ള അടിയന്തര കോൺടാക്റ്റുകൾ',
    reportEmergency: 'അടിയന്തരാവസ്ഥ റിപ്പോർട്ട് ചെയ്യുക',
    emergencyType: 'അടിയന്തരാവസ്ഥ തരം',
    selectEmergencyType: 'അടിയന്തരാവസ്ഥ തരം തിരഞ്ഞെടുക്കുക',
    medicalEmergency: 'മെഡിക്കൽ അടിയന്തരാവസ്ഥ',
    accident: 'അപകടം',
    fire: 'തീ',
    crime: 'കുറ്റകൃത്യം/അക്രമം',
    mentalHealthCrisis: 'മാനസികാരോഗ്യ പ്രതിസന്ധി',
    currentLocation: 'നിലവിലെ സ്ഥലം',
    locationPlaceholder: 'നിങ്ങളുടെ നിലവിലെ സ്ഥലം നൽകുക',
    getDescription: 'വിവരണം',
    descriptionPlaceholder: 'അടിയന്തരാവസ്ഥയുടെ സാഹചര്യം വിവരിക്കുക...',
    emergencyContactName: 'അടിയന്തര കോൺടാക്റ്റിന്റെ പേര്',
    contactNamePlaceholder: 'കോൺടാക്റ്റ് വ്യക്തിയുടെ പേര്',
    emergencyContactPhone: 'അടിയന്തര കോൺടാക്റ്റ് ഫോൺ',
    contactPhonePlaceholder: 'കോൺടാക്റ്റ് ഫോൺ നമ്പർ',
    submitEmergency: 'അടിയന്തരാവസ്ഥ സമർപ്പിക്കുക',
    importantNotice: 'പ്രധാന അറിയിപ്പ്',
    emergencyNoticeContent: 'അടിയന്തര ജീവൻ അപകടപ്പെടുത്തുന്ന സാഹചര്യങ്ങളിൽ, 911-ൽ നേരിട്ട് വിളിക്കുക. ഈ ഫോം റിപ്പോർട്ടിംഗിനും ട്രാക്കിംഗിനും മാത്രമുള്ളതാണ്, തൽക്ഷണ പ്രതികരണം നൽകിയേക്കില്ല.',
    getYourLocation: 'എന്റെ സ്ഥാനം നേടുക',
    submitting: 'സമർപ്പിക്കുന്നു...',
    emergencySent: 'അടിയന്തര റിപ്പോർട്ട് സമർപ്പിച്ചു! സഹായം വരുന്നുണ്ട്.',
    emergencyFailed: 'അടിയന്തര റിപ്പോർട്ട് സമർപ്പിക്കുന്നതിൽ പരാജയപ്പെട്ടു. ദയവായി 911-ൽ നേരിട്ട് വിളിക്കുക.',

    // Chatbot Modal
    chatAssistantTitle: 'ഹെൽത്ത്ബോട്ട് അസിസ്റ്റന്റ്',
    chatAssistantSubtitle: 'നിങ്ങളുടെ AI-അധിഷ്ഠിത ആരോഗ്യ കൂട്ടാളി',
    askHealthQuestion: 'ഒരു ആരോഗ്യ ചോദ്യം ചോദിക്കുക...'
  },
  pa: {
    // Navigation & Global
    login: 'ਲਾਗਇਨ',
    register: 'ਰਜਿਸਟਰ',
    logout: 'ਲੌਗਆਊਟ',
    back: 'ਵਾਪਸ',
    common: 'ਆਮ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    error: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ',
    success: 'ਸਫਲਤਾ!',
    cancel: 'ਰੱਦ ਕਰੋ',
    save: 'ਸੇਵ ਕਰੋ',
    edit: 'ਸੰਪਾਦਿਤ ਕਰੋ',
    delete: 'ਹਟਾਓ',
    
    // Landing Page
    appName: 'ਮੇਰਾ ਹੈਲਥਬੋਟ',
    motto: 'ਤੰਦਰੁਸਤ ਜੀਵਨ ਲਈ ਤੁਹਾਡਾ 24/7 ਦੇਖਭਾਲ ਕਰਨ ਵਾਲਾ ਵਰਚੁਅਲ ਸਾਥੀ',
    landingTitle: 'ਤੁਹਾਡੀ ਸਿਹਤ, ਸਾਡੀ ਪਹਿਲ',
    landingSubtitle: 'ਸਿਹਤ ਸੰਭਾਲ ਪੇਸ਼ੇਵਰਾਂ ਨਾਲ ਜੁੜੋ, ਤੁਰੰਤ ਡਾਕਟਰੀ ਸਲਾਹ ਲਵੋ, ਅਤੇ ਸਾਡੇ AI-ਪਾਵਰਡ ਸਿਹਤ ਸਹਾਇਕ ਨਾਲ ਆਪਣੀ ਤੰਦਰੁਸਤੀ ਦਾ ਸਫ਼ਰ ਬਰਕਰਾਰ ਰੱਖੋ।',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    
    // Login Page
    loginTitle: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    loginSubtitle: 'ਆਪਣੀ ਸਿਹਤ ਦਾ ਸਫ਼ਰ ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ',
    email: 'ਈਮੇਲ',
    password: 'ਪਾਸਵਰਡ',
    emailPlaceholder: 'ਆਪਣਾ ਈਮੇਲ ਦਾਖਲ ਕਰੋ',
    passwordPlaceholder: 'ਆਪਣਾ ਪਾਸਵਰਡ ਦਾਖਲ ਕਰੋ',
    signIn: 'ਸਾਈਨ ਇਨ',
    noAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    signUp: 'ਸਾਈਨ ਅੱਪ',
    forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ ਹੋ?',
    
    // Register Page
    registerTitle: 'ਖਾਤਾ ਬਣਾਓ',
    registerSubtitle: 'ਆਪਣੀ ਸਿਹਤ ਦੇ ਸਫ਼ਰ ਵਿੱਚ ਹਜ਼ਾਰਾਂ ਉਪਭੋਗਤਾਵਾਂ ਨਾਲ ਜੁੜੋ',
    fullName: 'ਪੂਰਾ ਨਾਮ',
    phone: 'ਫ਼ੋਨ ਨੰਬਰ',
    confirmPassword: 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    namePlaceholder: 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਾਖਲ ਕਰੋ',
    phonePlaceholder: 'ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਾਖਲ ਕਰੋ',
    confirmPasswordPlaceholder: 'ਆਪਣੇ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    alreadyHaveAccount: 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?',
    
    // Home Page
    welcome: 'ਸੁਆਗਤ ਹੈ',
    dashboardTitle: 'ਸਿਹਤ ਡੈਸ਼ਬੋਰਡ',
    bookAppointment: 'ਅਪਾਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ',
    emergencySOS: 'ਐਮਰਜੈਂਸੀ SOS',
    healthCheckup: 'ਸਿਹਤ ਜਾਂਚ',
    dietSuggestions: 'ਖੁਰਾਕ ਸੁਝਾਅ',
    exercisePlans: 'ਕਸਰਤ ਯੋਜਨਾਵਾਂ',
    mentalHealth: 'ਮਾਨਸਿਕ ਸਿਹਤ ਸਹਾਇਤਾ',
    healthReports: 'ਸਿਹਤ ਰਿਪੋਰਟਾਂ',
    
    // Symptom Scanner
    symptomScanner: 'ਲੱਛਣ ਸਕੈਨਰ',
    scanSymptoms: 'ਲੱਛਣਾਂ ਨੂੰ ਸਕੈਨ ਕਰੋ',

    // Book Appointment Modal
    bookAppointmentTitle: 'ਅਪਾਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ',
    scheduleConsultation: 'ਆਪਣੇ ਸਲਾਹ-ਮਸ਼ਵਰੇ ਦਾ ਸਮਾਂ ਨਿਸ਼ਚਿਤ ਕਰੋ',
    patientDetails: 'ਮਰੀਜ਼ ਦੇ ਵੇਰਵੇ',
    doctorSelection: 'ਡਾਕਟਰ ਦੀ ਚੋਣ',
    appointmentDetails: 'ਅਪਾਇੰਟਮੈਂਟ ਦੇ ਵੇਰਵੇ',
    previousReports: 'ਪਿਛਲੀਆਂ ਰਿਪੋਰਟਾਂ',
    uploadReportFormats: 'ਸਮਰਥਿਤ ਫਾਰਮੈਟ: PDF, JPG, PNG (ਅਧਿਕਤਮ 10MB)',
    uploadReportNote: 'ਪਿਛਲੀਆਂ ਮੈਡੀਕਲ ਰਿਪੋਰਟਾਂ ਅੱਪਲੋਡ ਕਰੋ (ਅਧਿਕਤਮ 5 ਫਾਈਲਾਂ)',
    uploadReportTitle: 'ਨਵੀਂ ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰੋ',
    selectDoctor: 'ਡਾਕਟਰ ਦੀ ਚੋਣ ਕਰੋ',
    chooseDoctor: 'ਇੱਕ ਡਾਕਟਰ ਚੁਣੋ',
    uploadFile: 'ਫਾਈਲ ਅੱਪਲੋਡ ਕਰੋ',
    reportType: 'ਰਿਪੋਰਟ ਦੀ ਕਿਸਮ',
    reportDate: 'ਰਿਪੋਰਟ ਦੀ ਤਾਰੀਖ',
    selectReportType: 'ਰਿਪੋਰਟ ਦੀ ਕਿਸਮ ਚੁਣੋ',
    bloodTest: 'ਖੂਨ ਦੀ ਜਾਂਚ',
    xray: 'ਐਕਸ-ਰੇ',
    mri: 'ਐਮਆਰਆਈ',
    ctscan: 'ਸੀਟੀ ਸਕੈਨ',
    ultrasound: 'ਅਲਟਰਾਸਾਊਂਡ',
    ecg: 'ਈਸੀਜੀ',
    prescription: 'ਨੁਸਖਾ',
    other: 'ਹੋਰ',
    notes: 'ਨੋਟਸ',
    notesPlaceholder: 'ਕੋਈ ਵਾਧੂ ਨੋਟਸ ਸ਼ਾਮਲ ਕਰੋ...',
    yourReports: 'ਤੁਹਾਡੀਆਂ ਰਿਪੋਰਟਾਂ',
    noReports: 'ਅਜੇ ਕੋਈ ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਨਹੀਂ ਕੀਤੀ ਗਈ',
    uploadFirstReport: 'ਉੱਪਰ ਆਪਣੀ ਪਹਿਲੀ ਮੈਡੀਕਲ ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰੋ',
    download: 'ਡਾਊਨਲੋਡ ਕਰੋ',
    failedToFetchReports: 'ਤੁਹਾਡੀਆਂ ਰਿਪੋਰਟਾਂ ਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    uploading: 'ਅੱਪਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    uploadReport: 'ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰੋ',
    reportUploaded: 'ਰਿਪੋਰਟ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਲੋਡ ਹੋਈ!',
    fileUploadFailed: 'ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    
    // Emergency Modal
    emergencyS0STitle: 'ਐਮਰਜੈਂਸੀ SOS',
    immediateHelp: 'ਤੁਰੰਤ ਮਦਦ ਲਵੋ',
    quickEmergencyContacts: 'ਤੁਰੰਤ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ',
    reportEmergency: 'ਐਮਰਜੈਂਸੀ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',
    emergencyType: 'ਐਮਰਜੈਂਸੀ ਦੀ ਕਿਸਮ',
    selectEmergencyType: 'ਐਮਰਜੈਂਸੀ ਦੀ ਕਿਸਮ ਚੁਣੋ',
    medicalEmergency: 'ਮੈਡੀਕਲ ਐਮਰਜੈਂਸੀ',
    accident: 'ਦੁਰਘਟਨਾ',
    fire: 'ਅੱਗ',
    crime: 'ਅਪਰਾਧ/ਹਿੰਸਾ',
    mentalHealthCrisis: 'ਮਾਨਸਿਕ ਸਿਹਤ ਸੰਕਟ',
    currentLocation: 'ਮੌਜੂਦਾ ਸਥਾਨ',
    locationPlaceholder: 'ਆਪਣਾ ਮੌਜੂਦਾ ਸਥਾਨ ਦਾਖਲ ਕਰੋ',
    getDescription: 'ਵਰਣਨ',
    descriptionPlaceholder: 'ਐਮਰਜੈਂਸੀ ਦੀ ਸਥਿਤੀ ਦਾ ਵਰਣਨ ਕਰੋ...',
    emergencyContactName: 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਦਾ ਨਾਮ',
    contactNamePlaceholder: 'ਸੰਪਰਕ ਵਿਅਕਤੀ ਦਾ ਨਾਮ',
    emergencyContactPhone: 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਫ਼ੋਨ',
    contactPhonePlaceholder: 'ਸੰਪਰਕ ਫ਼ੋਨ ਨੰਬਰ',
    submitEmergency: 'ਐਮਰਜੈਂਸੀ ਸਬਮਿਟ ਕਰੋ',
    importantNotice: 'ਮਹੱਤਵਪੂਰਨ ਸੂਚਨਾ',
    emergencyNoticeContent: 'ਤੁਰੰਤ ਜਾਨਲੇਵਾ ਐਮਰਜੈਂਸੀ ਲਈ, ਸਿੱਧਾ 911 ਤੇ ਕਾਲ ਕਰੋ। ਇਹ ਫਾਰਮ ਸਿਰਫ਼ ਰਿਪੋਰਟਿੰਗ ਅਤੇ ਟਰੈਕਿੰਗ ਦੇ ਉਦੇਸ਼ਾਂ ਲਈ ਹੈ ਅਤੇ ਤੁਰੰਤ ਜਵਾਬ ਨਹੀਂ ਦੇ ਸਕਦਾ ਹੈ।',
    getYourLocation: 'ਮੇਰਾ ਸਥਾਨ ਪ੍ਰਾਪਤ ਕਰੋ',
    submitting: 'ਸਬਮਿਟ ਹੋ ਰਿਹਾ ਹੈ...',
    emergencySent: 'ਐਮਰਜੈਂਸੀ ਦੀ ਬੇਨਤੀ ਸਬਮਿਟ ਹੋ ਗਈ! ਮਦਦ ਰਾਹ ਵਿੱਚ ਹੈ।',
    emergencyFailed: 'ਐਮਰਜੈਂਸੀ ਰਿਪੋਰਟ ਸਬਮਿਟ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਸਿੱਧਾ 911 ਤੇ ਕਾਲ ਕਰੋ।',

    // Chatbot Modal
    chatAssistantTitle: 'ਹੈਲਥਬੋਟ ਸਹਾਇਕ',
    chatAssistantSubtitle: 'ਤੁਹਾਡਾ AI-ਪਾਵਰਡ ਸਿਹਤ ਸਾਥੀ',
    askHealthQuestion: 'ਇੱਕ ਸਿਹਤ ਸਵਾਲ ਪੁੱਛੋ...'
  },
  gu: {
    // Navigation & Global
    login: 'લોગિન',
    register: 'નોંધણી',
    logout: 'લોગઆઉટ',
    back: 'પાછા',
    common: 'સામાન્ય',
    loading: 'લોડ થઈ રહ્યું છે...',
    error: 'કંઈક ખોટું થયું',
    success: 'સફળતા!',
    cancel: 'રદ કરો',
    save: 'સાચવો',
    edit: 'સંપાદિત કરો',
    delete: 'કાઢી નાખો',
    
    // Landing Page
    appName: 'માય હેલ્થબોટ',
    motto: 'સ્વસ્થ જીવન માટે તમારો 24/7 કાળજી લેતો વર્ચ્યુઅલ સાથી',
    landingTitle: 'તમારું સ્વાસ્થ્ય, અમારી પ્રાથમિકતા',
    landingSubtitle: 'આરોગ્ય સંભાળ વ્યાવસાયિકો સાથે જોડાઓ, ત્વરિત તબીબી સલાહ મેળવો, અને અમારા AI-સંચાલિત આરોગ્ય સહાયક સાથે તમારી તંદુરસ્તીની યાત્રા જાળવી રાખો.',
    getStarted: 'શરૂ કરો',
    
    // Login Page
    loginTitle: 'ફરીથી સ્વાગત છે',
    loginSubtitle: 'તમારી સ્વાસ્થ્ય યાત્રા ચાલુ રાખવા માટે સાઇન ઇન કરો',
    email: 'ઈમેલ',
    password: 'પાસવર્ડ',
    emailPlaceholder: 'તમારું ઇમેલ દાખલ કરો',
    passwordPlaceholder: 'તમારો પાસવર્ડ દાખલ કરો',
    signIn: 'સાઇન ઇન',
    noAccount: 'ખાતું નથી?',
    signUp: 'સાઇન અપ',
    forgotPassword: 'પાસવર્ડ ભૂલી ગયા?',
    
    // Register Page
    registerTitle: 'ખાતું બનાવો',
    registerSubtitle: 'તમારી સ્વાસ્થ્ય યાત્રામાં હજારો વપરાશકર્તાઓ સાથે જોડાઓ',
    fullName: 'પૂરું નામ',
    phone: 'ફોન નંબર',
    confirmPassword: 'પાસવર્ડની પુષ્ટિ કરો',
    namePlaceholder: 'તમારું પૂરું નામ દાખલ કરો',
    phonePlaceholder: 'તમારો ફોન નંબર દાખલ કરો',
    confirmPasswordPlaceholder: 'તમારા પાસવર્ડની પુષ્ટિ કરો',
    createAccount: 'ખાતું બનાવો',
    alreadyHaveAccount: 'પહેલેથી જ ખાતું છે?',
    
    // Home Page
    welcome: 'સ્વાગત',
    dashboardTitle: 'સ્વાસ્થ્ય ડેશબોર્ડ',
    bookAppointment: 'એપોઇન્ટમેન્ટ બુક કરો',
    emergencySOS: 'આપત્તિ SOS',
    healthCheckup: 'સ્વાસ્થ્ય તપાસ',
    dietSuggestions: 'આહાર સૂચનો',
    exercisePlans: 'વ્યાયામ યોજનાઓ',
    mentalHealth: 'માનસિક સ્વાસ્થ્ય સહાય',
    healthReports: 'આરોગ્ય અહેવાલો',
    
    // Symptom Scanner
    symptomScanner: 'લક્ષણ સ્કેનર',
    scanSymptoms: 'લક્ષણો સ્કેન કરો',

    // Book Appointment Modal
    bookAppointmentTitle: 'એપોઇન્ટમેન્ટ બુક કરો',
    scheduleConsultation: 'તમારા પરામર્શનું સમયપત્રક બનાવો',
    patientDetails: 'દર્દીની વિગતો',
    doctorSelection: 'ડૉક્ટરની પસંદગી',
    appointmentDetails: 'એપોઇન્ટમેન્ટની વિગતો',
    previousReports: 'પાછલા અહેવાલો',
    uploadReportFormats: 'સપોર્ટેડ ફોર્મેટ્સ: PDF, JPG, PNG (મહત્તમ 10MB)',
    uploadReportNote: 'પાછલા તબીબી અહેવાલો અપલોડ કરો (મહત્તમ 5 ફાઇલો)',
    uploadReportTitle: 'નવો અહેવાલ અપલોડ કરો',
    selectDoctor: 'ડૉક્ટર પસંદ કરો',
    chooseDoctor: 'એક ડૉક્ટર પસંદ કરો',
    uploadFile: 'ફાઇલ અપલોડ કરો',
    reportType: 'અહેવાલનો પ્રકાર',
    reportDate: 'અહેવાલની તારીખ',
    selectReportType: 'અહેવાલનો પ્રકાર પસંદ કરો',
    bloodTest: 'રક્ત પરીક્ષણ',
    xray: 'એક્સ-રે',
    mri: 'એમઆરઆઈ',
    ctscan: 'સીટી સ્કેન',
    ultrasound: 'અલ્ટ્રાસાઉન્ડ',
    ecg: 'ઇસીજી',
    prescription: 'પ્રિસ્ક્રિપ્શન',
    other: 'અન્ય',
    notes: 'નોંધો',
    notesPlaceholder: 'કોઈપણ વધારાની નોંધો ઉમેરો...',
    yourReports: 'તમારા અહેવાલો',
    noReports: 'હજુ સુધી કોઈ અહેવાલો અપલોડ કરવામાં આવ્યા નથી',
    uploadFirstReport: 'ઉપર તમારો પ્રથમ તબીબી અહેવાલ અપલોડ કરો',
    download: 'ડાઉનલોડ કરો',
    failedToFetchReports: 'તમારા અહેવાલો લોડ કરવામાં નિષ્ફળ. કૃપા કરીને ફરીથી પ્રયાસ કરો.',
    uploading: 'અપલોડ થઈ રહ્યું છે...',
    uploadReport: 'અહેવાલ અપલોડ કરો',
    reportUploaded: 'અહેવાલ સફળતાપૂર્વક અપલોડ થયો!',
    fileUploadFailed: 'અહેવાલ અપલોડ કરવામાં નિષ્ફળ. કૃપા કરીને ફરીથી પ્રયાસ કરો.',

    // Emergency Modal
    emergencyS0STitle: 'આપત્તિ SOS',
    immediateHelp: 'તાત્કાલિક મદદ મેળવો',
    quickEmergencyContacts: 'ઝડપી આપત્તિ સંપર્કો',
    reportEmergency: 'આપત્તિની જાણ કરો',
    emergencyType: 'આપત્તિનો પ્રકાર',
    selectEmergencyType: 'આપત્તિનો પ્રકાર પસંદ કરો',
    medicalEmergency: 'તબીબી આપત્તિ',
    accident: 'અકસ્માત',
    fire: 'આગ',
    crime: 'ગુનો/હિંસા',
    mentalHealthCrisis: 'માનસિક સ્વાસ્થ્ય કટોકટી',
    currentLocation: 'વર્તમાન સ્થાન',
    locationPlaceholder: 'તમારું વર્તમાન સ્થાન દાખલ કરો',
    getDescription: 'વર્ણન',
    descriptionPlaceholder: 'આપત્તિની સ્થિતિનું વર્ણન કરો...',
    emergencyContactName: 'આપત્તિ સંપર્કનું નામ',
    contactNamePlaceholder: 'સંપર્ક વ્યક્તિનું નામ',
    emergencyContactPhone: 'આપત્તિ સંપર્ક ફોન',
    contactPhonePlaceholder: 'સંપર્ક ફોન નંબર',
    submitEmergency: 'આપત્તિ સબમિટ કરો',
    importantNotice: 'મહત્વપૂર્ણ સૂચના',
    emergencyNoticeContent: 'તાત્કાલિક જીવન માટે જોખમી આપત્તિઓ માટે, સીધો 911 પર કૉલ કરો. આ ફોર્મ ફક્ત રિપોર્ટિંગ અને ટ્રેકિંગ હેતુઓ માટે છે અને તાત્કાલિક પ્રતિસાદ આપી શકશે નહીં.',
    getYourLocation: 'મારું સ્થાન મેળવો',
    submitting: 'સબમિટ થઈ રહ્યું છે...',
    emergencySent: 'આપત્તિની વિનંતી સબમિટ થઈ! મદદ રસ્તામાં છે.',
    emergencyFailed: 'આપત્તિ અહેવાલ સબમિટ કરવામાં નિષ્ફળ. કૃપા કરીને સીધો 911 પર કૉલ કરો.',

    // Chatbot Modal
    chatAssistantTitle: 'હેલ્થબોટ સહાયક',
    chatAssistantSubtitle: 'તમારો AI-સંચાલિત સ્વાસ્થ્ય સાથી',
    askHealthQuestion: 'એક સ્વાસ્થ્ય પ્રશ્ન પૂછો...'
  },
  or: {
    // Navigation & Global
    login: 'ଲଗଇନ୍',
    register: 'ପଞ୍ଜୀକରଣ',
    logout: 'ଲଗ୍ ଆଉଟ୍',
    back: 'ପଛକୁ',
    common: 'ସାଧାରଣ',
    loading: 'ଲୋଡ୍ ହେଉଛି...',
    error: 'କିଛି ଭୁଲ୍ ହୋଇଗଲା',
    success: 'ସଫଳ!',
    cancel: 'ବାତିଲ କରନ୍ତୁ',
    save: 'ସେଭ୍ କରନ୍ତୁ',
    edit: 'ସମ୍ପାଦନା କରନ୍ତୁ',
    delete: 'ଲିଭାନ୍ତୁ',
    
    // Landing Page
    appName: 'ମାଇଁ ହେଲ୍ଥବଟ୍',
    motto: 'ଏକ ସୁସ୍ଥ ଜୀବନ ପାଇଁ ଆପଣଙ୍କର 24/7 ଯତ୍ନବାନ ଭର୍ଚୁଆଲ୍ ସାଥୀ',
    landingTitle: 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ, ଆମର ପ୍ରାଥମିକତା',
    landingSubtitle: 'ସ୍ୱାସ୍ଥ୍ୟସେବା ବ୍ୟବସାୟୀଙ୍କ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ, ତୁରନ୍ତ ଡାକ୍ତରୀ ପରାମର୍ଶ ପାଆନ୍ତୁ, ଏବଂ ଆମର AI-ସକ୍ଷମ ସ୍ୱାସ୍ଥ୍ୟ ସହାୟକ ସହିତ ଆପଣଙ୍କର ସୁସ୍ଥତା ଯାତ୍ରା ବଜାୟ ରଖନ୍ତୁ।',
    getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ',
    
    // Login Page
    loginTitle: 'ପୁନର୍ବାର ସ୍ୱାଗତ',
    loginSubtitle: 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ ଯାତ୍ରା ଜାରି ରଖିବା ପାଇଁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    email: 'ଇମେଲ',
    password: 'ପାସୱାର୍ଡ',
    emailPlaceholder: 'ଆପଣଙ୍କ ଇମେଲ ଦାଖଲ କରନ୍ତୁ',
    passwordPlaceholder: 'ଆପଣଙ୍କ ପାସୱାର୍ଡ ଦାଖଲ କରନ୍ତୁ',
    signIn: 'ସାଇନ୍ ଇନ୍',
    noAccount: 'ଆକାଉଣ୍ଟ ନାହିଁ?',
    signUp: 'ସାଇନ୍ ଅପ୍',
    forgotPassword: 'ପାସୱାର୍ଡ ଭୁଲିଗଲେ?',
    
    // Register Page
    registerTitle: 'ଆକାଉଣ୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ',
    registerSubtitle: 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ ଯାତ୍ରାରେ ହଜାର ହଜାର ଉପଭୋକ୍ତାଙ୍କ ସହିତ ଯୋଗ ଦିଅନ୍ତୁ',
    fullName: 'ପୂରା ନାମ',
    phone: 'ଫୋନ୍ ନମ୍ବର',
    confirmPassword: 'ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ',
    namePlaceholder: 'ଆପଣଙ୍କର ପୂରା ନାମ ଦାଖଲ କରନ୍ତୁ',
    phonePlaceholder: 'ଆପଣଙ୍କର ଫୋନ୍ ନମ୍ବର ଦାଖଲ କରନ୍ତୁ',
    confirmPasswordPlaceholder: 'ଆପଣଙ୍କ ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ',
    createAccount: 'ଆକାଉଣ୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ',
    alreadyHaveAccount: 'ଆଗରୁ ଆକାଉଣ୍ଟ ଅଛି?',
    
    // Home Page
    welcome: 'ସ୍ୱାଗତ',
    dashboardTitle: 'ସ୍ୱାସ୍ଥ୍ୟ ଡାସବୋର୍ଡ',
    bookAppointment: 'ଏପଏଣ୍ଟମେଣ୍ଟ ବୁକ୍ କରନ୍ତୁ',
    emergencySOS: 'ଜରୁରୀକାଳୀନ SOS',
    healthCheckup: 'ସ୍ୱାସ୍ଥ୍ୟ ଯାଞ୍ଚ',
    dietSuggestions: 'ଖାଦ୍ୟ ପରାମର୍ଶ',
    exercisePlans: 'ବ୍ୟାୟାମ ଯୋଜନା',
    mentalHealth: 'ମାନସିକ ସ୍ୱାସ୍ଥ୍ୟ ସହାୟତା',
    healthReports: 'ସ୍ୱାସ୍ଥ୍ୟ ରିପୋର୍ଟ',
    
    // Symptom Scanner
    symptomScanner: 'ଲକ୍ଷଣ ସ୍କାନର୍',
    scanSymptoms: 'ଲକ୍ଷଣ ସ୍କାନ କରନ୍ତୁ',

    // Book Appointment Modal
    bookAppointmentTitle: 'ଏପଏଣ୍ଟମେଣ୍ଟ ବୁକ୍ କରନ୍ତୁ',
    scheduleConsultation: 'ଆପଣଙ୍କ ପରାମର୍ଶକୁ ସିଡ୍ୟୁଲ୍ କରନ୍ତୁ',
    patientDetails: 'ରୋଗୀଙ୍କ ବିବରଣୀ',
    doctorSelection: 'ଡାକ୍ତର ଚୟନ',
    appointmentDetails: 'ଏପଏଣ୍ଟମେଣ୍ଟ ବିବରଣୀ',
    previousReports: 'ପୂର୍ବ ରିପୋର୍ଟ',
    uploadReportFormats: 'ସମର୍ଥିତ ଫର୍ମାଟ୍: PDF, JPG, PNG (ସର୍ବାଧିକ 10MB)',
    uploadReportNote: 'ପୂର୍ବ ମେଡିକାଲ୍ ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ (ସର୍ବାଧିକ 5 ଫାଇଲ୍)',
    uploadReportTitle: 'ନୂଆ ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
    selectDoctor: 'ଡାକ୍ତର ଚୟନ କରନ୍ତୁ',
    chooseDoctor: 'ଜଣେ ଡାକ୍ତର ବାଛନ୍ତୁ',
    uploadFile: 'ଫାଇଲ୍ ଅପଲୋଡ୍ କରନ୍ତୁ',
    reportType: 'ରିପୋର୍ଟ ପ୍ରକାର',
    reportDate: 'ରିପୋର୍ଟ ତାରିଖ',
    selectReportType: 'ରିପୋର୍ଟ ପ୍ରକାର ଚୟନ କରନ୍ତୁ',
    bloodTest: 'ରକ୍ତ ପରୀକ୍ଷା',
    xray: 'ଏକ୍ସ-ରେ',
    mri: 'ଏମଆରଆଇ',
    ctscan: 'ସିଟି ସ୍କାନ୍',
    ultrasound: 'ଅଲଟ୍ରାସାଉଣ୍ଡ',
    ecg: 'ଇସିଜି',
    prescription: 'ପ୍ରେସକ୍ରିପସନ୍',
    other: 'ଅନ୍ୟାନ୍ୟ',
    notes: 'ଟିପ୍ପଣୀ',
    notesPlaceholder: 'କୌଣସି ଅତିରିକ୍ତ ଟିପ୍ପଣୀ ଯୋଡନ୍ତୁ...',
    yourReports: 'ଆପଣଙ୍କ ରିପୋର୍ଟ',
    noReports: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ରିପୋର୍ଟ ଅପଲୋଡ୍ ହୋଇନାହିଁ',
    uploadFirstReport: 'ଉପରେ ଆପଣଙ୍କର ପ୍ରଥମ ମେଡିକାଲ୍ ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
    download: 'ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
    failedToFetchReports: 'ଆପଣଙ୍କ ରିପୋର୍ଟଗୁଡ଼ିକୁ ଲୋଡ୍ କରିବାରେ ବିଫଳ। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
    uploading: 'ଅପଲୋଡ୍ ହେଉଛି...',
    uploadReport: 'ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
    reportUploaded: 'ରିପୋର୍ଟ ସଫଳତାର ସହ ଅପଲୋଡ୍ ହୋଇଛି!',
    fileUploadFailed: 'ରିପୋର୍ଟ ଅପଲୋଡ୍ କରିବାରେ ବିଫଳ। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',

    // Emergency Modal
    emergencyS0STitle: 'ଜରୁରୀକାଳୀନ SOS',
    immediateHelp: 'ତୁରନ୍ତ ସାହାଯ୍ୟ ପାଆନ୍ତୁ',
    quickEmergencyContacts: 'ଶୀଘ୍ର ଜରୁରୀକାଳୀନ ଯୋଗାଯୋଗ',
    reportEmergency: 'ଜରୁରୀକାଳୀନ ପରିସ୍ଥିତି ରିପୋର୍ଟ କରନ୍ତୁ',
    emergencyType: 'ଜରୁରୀକାଳୀନ ପ୍ରକାର',
    selectEmergencyType: 'ଜରୁରୀକାଳୀନ ପ୍ରକାର ଚୟନ କରନ୍ତୁ',
    medicalEmergency: 'ଡାକ୍ତରୀ ଜରୁରୀକାଳୀନ',
    accident: 'ଦୁର୍ଘଟଣା',
    fire: 'ଅଗ୍ନି',
    crime: 'ଅପରାଧ/ହିଂସା',
    mentalHealthCrisis: 'ମାନସିକ ସ୍ୱାସ୍ଥ୍ୟ ସଙ୍କଟ',
    currentLocation: 'ବର୍ତ୍ତମାନର ଅବସ୍ଥାନ',
    locationPlaceholder: 'ଆପଣଙ୍କର ବର୍ତ୍ତମାନର ଅବସ୍ଥାନ ଦାଖଲ କରନ୍ତୁ',
    getDescription: 'ବର୍ଣ୍ଣନା',
    descriptionPlaceholder: 'ଜରୁରୀକାଳୀନ ପରିସ୍ଥିତିର ବର୍ଣ୍ଣନା କରନ୍ତୁ...',
    emergencyContactName: 'ଜରୁରୀକାଳୀନ ଯୋଗାଯୋଗ ନାମ',
    contactNamePlaceholder: 'ଯୋଗାଯୋଗ ବ୍ୟକ୍ତିଙ୍କ ନାମ',
    emergencyContactPhone: 'ଜରୁରୀକାଳୀନ ଯୋଗାଯୋଗ ଫୋନ୍',
    contactPhonePlaceholder: 'ଯୋଗାଯୋଗ ଫୋନ୍ ନମ୍ବର',
    submitEmergency: 'ଜରୁରୀକାଳୀନ ପରିସ୍ଥିତି ଦାଖଲ କରନ୍ତୁ',
    importantNotice: 'ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ସୂଚନା',
    emergencyNoticeContent: 'ତୁରନ୍ତ ଜୀବନ ପ୍ରତି ବିପଦ ଥିବା ଜରୁରୀକାଳୀନ ପରିସ୍ଥିତି ପାଇଁ, ସିଧାସଳଖ 911 କୁ କଲ୍ କରନ୍ତୁ। ଏହି ଫର୍ମ କେବଳ ରିପୋର୍ଟ ଏବଂ ଟ୍ରାକିଂ ଉଦ୍ଦେଶ୍ୟ ପାଇଁ ଅଟେ ଏବଂ ତୁରନ୍ତ ପ୍ରତିକ୍ରିୟା ଯୋଗାଇ ନ ପାରେ।',
    getYourLocation: 'ମୋର ଅବସ୍ଥାନ ପାଆନ୍ତୁ',
    submitting: 'ଦାଖଲ ହେଉଛି...',
    emergencySent: 'ଜରୁରୀକାଳୀନ ଅନୁରୋଧ ଦାଖଲ ହୋଇଛି! ସାହାଯ୍ୟ ରାସ୍ତାରେ ଅଛି।',
    emergencyFailed: 'ଜରୁରୀକାଳୀନ ରିପୋର୍ଟ ଦାଖଲ କରିବାରେ ବିଫଳ। ଦୟାକରି ସିଧାସଳଖ 911 କୁ କଲ୍ କରନ୍ତୁ।',

    // Chatbot Modal
    chatAssistantTitle: 'ହେଲ୍ଥବଟ୍ ସହାୟକ',
    chatAssistantSubtitle: 'ଆପଣଙ୍କ AI-ସକ୍ଷମ ସ୍ୱାସ୍ଥ୍ୟ ସାଥୀ',
    askHealthQuestion: 'ସ୍ୱାସ୍ଥ୍ୟ ସମ୍ବନ୍ଧୀୟ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ...'
  },
  as: {
    // Navigation & Global
    login: 'লগইন',
    register: 'পঞ্জীয়ন',
    logout: 'লগআউট',
    back: 'পিছলৈ',
    common: 'সাধাৰণ',
    loading: 'ল’ড হৈ আছে...',
    error: 'কিবা ভুল হৈছে',
    success: 'সফল!',
    cancel: 'বাতিল কৰক',
    save: 'সংৰক্ষণ কৰক',
    edit: 'সম্পাদনা কৰক',
    delete: 'বিলোপ কৰক',
    
    // Landing Page
    appName: 'মোৰ হেলথবট',
    motto: 'সুস্বাস্থ্যৰ বাবে আপোনাৰ ২৪/৭ যত্নশীল ভাৰ্চুৱেল সংগী',
    landingTitle: 'আপোনাৰ স্বাস্থ্য, আমাৰ অগ্ৰাধিকাৰ',
    landingSubtitle: 'স্বাস্থ্যসেৱা পেছাদাৰীসকলৰ সৈতে সংযোগ স্থাপন কৰক, তাৎক্ষণিক চিকিৎসা পৰামৰ্শ পাওক আৰু আমাৰ AI-চালিত স্বাস্থ্য সহায়কৰ সৈতে আপোনাৰ সুস্থতাৰ যাত্ৰা অব্যাহত ৰাখক।',
    getStarted: 'আৰম্ভ কৰক',
    
    // Login Page
    loginTitle: 'পুনৰ স্বাগতম',
    loginSubtitle: 'আপোনাৰ স্বাস্থ্য যাত্ৰা অব্যাহত ৰাখিবলৈ চাইন ইন কৰক',
    email: 'ইমেইল',
    password: 'পাছৱৰ্ড',
    emailPlaceholder: 'আপোনাৰ ইমেইল দাখিল কৰক',
    passwordPlaceholder: 'আপোনাৰ পাছৱৰ্ড দাখিল কৰক',
    signIn: 'চাই ইন',
    noAccount: 'এটা একাউণ্ট নাই?',
    signUp: 'চাই আপ',
    forgotPassword: 'পাছৱৰ্ড পাহৰি গ\'ল?',
    
    // Register Page
    registerTitle: 'একাউণ্ট সৃষ্টি কৰক',
    registerSubtitle: 'আপোনাৰ স্বাস্থ্য যাত্ৰাত হাজাৰ হাজাৰ ব্যৱহাৰকাৰীৰ সৈতে যোগ দিয়ক',
    fullName: 'পূৰ্ণ নাম',
    phone: 'ফোন নম্বৰ',
    confirmPassword: 'পাছৱৰ্ড নিশ্চিত কৰক',
    namePlaceholder: 'আপোনাৰ পূৰ্ণ নাম দাখিল কৰক',
    phonePlaceholder: 'আপোনাৰ ফোন নম্বৰ দাখিল কৰক',
    confirmPasswordPlaceholder: 'আপোনাৰ পাছৱৰ্ড নিশ্চিত কৰক',
    createAccount: 'একাউণ্ট সৃষ্টি কৰক',
    alreadyHaveAccount: 'ইতিমধ্যে একাউণ্ট আছে?',
    
    // Home Page
    welcome: 'স্বাগতম',
    dashboardTitle: 'স্বাস্থ্য ডেশ্বোৰ্ড',
    bookAppointment: 'এপইণ্টমেন্ট বুক কৰক',
    emergencySOS: 'জৰুৰী SOS',
    healthCheckup: 'স্বাস্থ্য পৰীক্ষা',
    dietSuggestions: 'আহাৰৰ পৰামৰ্শ',
    exercisePlans: 'ব্যায়ামৰ পৰিকল্পনা',
    mentalHealth: 'মানসিক স্বাস্থ্যৰ সহায়',
    healthReports: 'স্বাস্থ্য প্ৰতিবেদন',
    
    // Symptom Scanner
    symptomScanner: 'লক্ষণ স্কেনাৰ',
    scanSymptoms: 'লক্ষণ স্কেন কৰক',

    // Book Appointment Modal
    bookAppointmentTitle: 'এপইণ্টমেন্ট বুক কৰক',
    scheduleConsultation: 'আপোনাৰ পৰামৰ্শসূচী নিৰ্ধাৰণ কৰক',
    patientDetails: 'ৰোগীৰ বিৱৰণ',
    doctorSelection: 'চিকিৎসকৰ নিৰ্বাচন',
    appointmentDetails: 'এপইণ্টমেন্টৰ বিৱৰণ',
    previousReports: 'পূৰ্বৰ প্ৰতিবেদন',
    uploadReportFormats: 'সমৰ্থিত ফৰ্মেট: PDF, JPG, PNG (সৰ্বাধিক 10MB)',
    uploadReportNote: 'পূৰ্বৰ চিকিৎসা প্ৰতিবেদন আপলোড কৰক (সৰ্বাধিক 5 টা ফাইল)',
    uploadReportTitle: 'নতুন প্ৰতিবেদন আপলোড কৰক',
    selectDoctor: 'চিকিৎসক নিৰ্বাচন কৰক',
    chooseDoctor: 'এজন চিকিৎসক বাছনি কৰক',
    uploadFile: 'ফাইল আপলোড কৰক',
    reportType: 'প্ৰতিবেদনৰ প্ৰকাৰ',
    reportDate: 'প্ৰতিবেদনৰ তাৰিখ',
    selectReportType: 'প্ৰতিবেদনৰ প্ৰকাৰ বাছনি কৰক',
    bloodTest: 'ৰক্ত পৰীক্ষা',
    xray: 'এক্স-ৰে',
    mri: 'এমআৰআই',
    ctscan: 'চিটি স্কেন',
    ultrasound: 'আল্ট্ৰাচাউণ্ড',
    ecg: 'ইচিজি',
    prescription: 'প্ৰেছক্ৰিপচন',
    other: 'অন্যান্য',
    notes: 'টোকা',
    notesPlaceholder: 'যিকোনো অতিৰিক্ত টোকা যোগ কৰক...',
    yourReports: 'আপোনাৰ প্ৰতিবেদন',
    noReports: 'এতিয়ালৈকে কোনো প্ৰতিবেদন আপলোড কৰা হোৱা নাই',
    uploadFirstReport: 'ওপৰত আপোনাৰ প্ৰথম চিকিৎসা প্ৰতিবেদন আপলোড কৰক',
    download: 'ডাউনলোড কৰক',
    failedToFetchReports: 'আপোনাৰ প্ৰতিবেদনসমূহ লোড কৰাত ব্যৰ্থ হৈছে। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।',
    uploading: 'আপলোড হৈ আছে...',
    uploadReport: 'প্ৰতিবেদন আপলোড কৰক',
    reportUploaded: 'প্ৰতিবেদন সফলভাৱে আপলোড কৰা হৈছে!',
    fileUploadFailed: 'প্ৰতিবেদন আপলোড কৰাত ব্যৰ্থ হৈছে। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।',
    
    // Emergency Modal
    emergencyS0STitle: 'জৰুৰী SOS',
    immediateHelp: 'জৰুৰী সাহায্য লাভ কৰক',
    quickEmergencyContacts: 'তৎক্ষণিক জৰুৰী যোগাযোগ',
    reportEmergency: 'জৰুৰী পৰিস্থিতিৰ প্ৰতিবেদন দিয়ক',
    emergencyType: 'জৰুৰী পৰিস্থিতিৰ প্ৰকাৰ',
    selectEmergencyType: 'জৰুৰী পৰিস্থিতিৰ প্ৰকাৰ বাছনি কৰক',
    medicalEmergency: 'চিকিৎসা জৰুৰী',
    accident: 'দুৰ্ঘটনা',
    fire: 'জুই',
    crime: 'অপৰাধ/হিংসা',
    mentalHealthCrisis: 'মানসিক স্বাস্থ্য সংকট',
    currentLocation: 'বৰ্তমানৰ স্থান',
    locationPlaceholder: 'আপোনাৰ বৰ্তমানৰ স্থান দাখিল কৰক',
    getDescription: 'বিৱৰণ',
    descriptionPlaceholder: 'জৰুৰী পৰিস্থিতিৰ বিৱৰণ দিয়ক...',
    emergencyContactName: 'জৰুৰীকালীন যোগাযোগৰ নাম',
    contactNamePlaceholder: 'যোগাযোগ কৰা ব্যক্তিৰ নাম',
    emergencyContactPhone: 'জৰুৰীকালীন যোগাযোগৰ ফোন',
    contactPhonePlaceholder: 'যোগাযোগৰ ফোন নম্বৰ',
    submitEmergency: 'জৰুৰীকালীন দাখিল কৰক',
    importantNotice: 'গুৰুত্বপূৰ্ণ জাননী',
    emergencyNoticeContent: 'তৎক্ষণিক জীৱন-প্ৰতি-বিপদজনক জৰুৰীকালীন পৰিস্থিতিৰ বাবে, পোনে পোনে 911-লৈ ফোন কৰক। এই ফৰ্মটো কেৱল প্ৰতিবেদন আৰু ট্ৰেকিংৰ উদ্দেশ্যৰ বাবেহে, আৰু তৎক্ষণিক সঁহাৰি নিদিয়াকৈ পাৰে।',
    getYourLocation: 'মোৰ স্থান লাভ কৰক',
    submitting: 'দাখিল হৈ আছে...',
    emergencySent: 'জৰুৰীকালীন অনুৰোধ দাখিল কৰা হৈছে! সাহায্য আহি আছে।',
    emergencyFailed: 'জৰুৰীকালীন প্ৰতিবেদন দাখিল কৰাত ব্যৰ্থ। অনুগ্ৰহ কৰি পোনে পোনে 911-লৈ ফোন কৰক।',

    // Chatbot Modal
    chatAssistantTitle: 'হেলথবট সহায়ক',
    chatAssistantSubtitle: 'আপোনাৰ AI-চালিত স্বাস্থ্য সংগী',
    askHealthQuestion: 'এক স্বাস্থ্য সম্পৰ্কীয় প্ৰশ্ন সুধিব...'
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>(() => {
    const storedLang = localStorage.getItem('appLanguage');
    const validLanguages: LanguageCode[] = ['en', 'hi', 'te', 'mr', 'bn', 'ta', 'kn', 'ml', 'pa', 'gu', 'or', 'as'];
    return (storedLang && validLanguages.includes(storedLang as LanguageCode)) ? (storedLang as LanguageCode) : 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};